// SPDX-License-Identifier: GPL-3.0-or-later
//! The stack paths the app reports, plus macOS service registration.
//! `StackPaths` is a portable data type defined for every target; only building
//! it is platform-specific. Data-only: binaries from the Homebrew probe
//! (resolved at registration time), configs generated by `site::apply` under
//! `<home>/config/generated/`. The generated tree is the ONLY config source —
//! see `openvhost_core::platform::macos::demo_stack::provision_home`, which
//! creates directories and seeds the welcome page but writes no config.

use std::ffi::OsString;
use std::path::{Path, PathBuf};
use std::time::Duration;

#[cfg(target_os = "macos")]
use openvhost_core::platform::macos::demo_stack::{BrewStack, find_brew_binaries, provision_home};
#[cfg(target_os = "macos")]
use openvhost_core::site::apply::LISTEN_PORT;
// Portable: `InstalledRuntimes`/`PhpRuntime` are plain data (see `StackPaths`'s
// own doc comment for why portable types are named ungated even though only
// `macos_stack` constructs them today), and `php_fpm_spec` below is called
// from `commands.rs`, which is ungated too.
use openvhost_core::mariadb::{
    MariadbDatadirState, MariadbRuntime, classify_mariadb_datadir, mariadb_paths,
};
use openvhost_core::mysql::{DatadirState, MysqlRuntime, classify_datadir, mysql_paths};
// Re-exported by `openvhost-core` so this crate needs no direct `openvhost-pkg`
// dependency. Minted only from a resolved home — never from IPC input.
use openvhost_core::PackagesRoot;
use openvhost_core::{InstalledRuntimes, PhpRuntime};
use openvhost_proc::{DEFAULT_GRACE, ReadinessProbe, ServiceSpec, SpawnSpec};

/// Apple Silicon default paths, used when probing finds nothing: the rows
/// still register, and Start yields an honest Failed naming the missing
/// path (the P0-3 spawn-fail contract) instead of the rows vanishing.
#[cfg(target_os = "macos")]
fn fallback_brew() -> BrewStack {
    BrewStack {
        nginx: PathBuf::from("/opt/homebrew/opt/nginx/bin/nginx"),
        php_fpm: PathBuf::from("/opt/homebrew/opt/php/sbin/php-fpm"),
    }
}

/// The paths the stack actually registered, so the Web Server page can report
/// them instead of re-probing and possibly disagreeing. Read out of the managed
/// `Option<StackPaths>` state by `commands::list_web_servers` and friends.
///
/// Portable by construction — three `PathBuf`s, nothing platform-specific — so
/// it is defined for EVERY target and `commands.rs` can name it ungated. Only
/// building one is platform-specific (`macos_stack` below); targets with no
/// stack builder manage `None`.
// On a target with no stack builder this type is named and its fields are read
// by ungated `commands.rs` code, but nothing CONSTRUCTS it, which is rustc's
// separate "struct is never constructed" dead_code diagnostic. Reproduced in
// isolation on rustc 1.96: that diagnostic does NOT fire for a struct whose
// fields are read from a reachable signature, so this allow is belt-and-braces
// rather than load-bearing. Kept because no non-macOS target can be compiled
// from this repo yet (libsqlite3-sys's bundled C blocks cross-checks) and the
// diagnostic's exact trigger has moved between releases, while the cost is nil:
// it is cfg'd OFF on macOS, where all three fields are genuinely read, so no
// dead-code signal is suppressed on the platform actually built here. Do NOT
// switch this to `#[expect]` — that warns when the lint does not fire, turning
// the unverifiable direction into a guaranteed break. A `#[cfg(not(macos))]`
// duplicate stub type is also not the answer: unverifiable code that drifts.
#[cfg_attr(not(target_os = "macos"), allow(dead_code))]
pub struct StackPaths {
    pub home: PathBuf,
    pub nginx_bin: PathBuf,
    pub nginx_conf: PathBuf,
}

/// The `php-fpm-<major>` service row for one runtime: id, display name,
/// endpoint (the pool's own socket) and the exact spawn spec.
///
/// Extracted so `macos_stack` (built once at startup) and the desktop crate's
/// PHP rescan/install commands (which register a row for a version installed
/// AFTER launch) build the row identically. Two independent copies of this
/// spec drifting apart would mean an installed-after-launch version serves
/// through a subtly different pool than one present at launch — a silent
/// correctness gap, not a crash, so nothing would fail loudly enough to catch
/// it.
///
/// Portable data construction — like `StackPaths`, only building the STACK
/// (`macos_stack`) is platform-specific today; this row-shape function is
/// not.
/// The `<prefix><major>` shape of every php-fpm service id. Split out as a
/// constant so the uninstall/rescan reconciliation can recognise one of OUR
/// pool rows (and strip the major back off it) without re-typing the literal
/// that [`php_fpm_service_id`] builds — the two must agree or a reconciliation
/// pass would either miss rows or match the wrong ones.
pub(crate) const PHP_FPM_ID_PREFIX: &str = "php-fpm-";

/// The `<prefix><major>` shape of every MySQL service id — see
/// [`PHP_FPM_ID_PREFIX`].
pub(crate) const MYSQL_ID_PREFIX: &str = "mysql-";

/// The supervisor id for one PHP major's pool. THE definition — every other
/// site (the uninstall inventory, the rescan reconciliation, the DTO the
/// Languages page drives start/stop from) derives it from here rather than
/// re-spelling the format string, because an id built two ways is an id that
/// eventually names two different rows.
pub fn php_fpm_service_id(major: &str) -> String {
    format!("{PHP_FPM_ID_PREFIX}{major}")
}

/// The `<prefix><series>` shape of every MariaDB service id — see
/// [`PHP_FPM_ID_PREFIX`].
///
/// It has to be a DIFFERENT prefix from [`MYSQL_ID_PREFIX`], not a different
/// version under the same one: this build's MariaDB series is `11.4`, and
/// MySQL majors are discovered from whatever is installed rather than from a
/// catalogue, so a machine carrying a `mysql@11.4` keg would produce the very
/// same id string. Two rows sharing one id is not a display bug — the
/// Supervisor keys its registry by id, so one engine would take over the
/// other's row.
pub(crate) const MARIADB_ID_PREFIX: &str = "mariadb-";

/// The supervisor id for one MySQL major — see [`php_fpm_service_id`].
pub fn mysql_service_id(major: &str) -> String {
    format!("{MYSQL_ID_PREFIX}{major}")
}

/// The supervisor id for one MariaDB series — see [`php_fpm_service_id`].
pub fn mariadb_service_id(series: &str) -> String {
    format!("{MARIADB_ID_PREFIX}{series}")
}

/// The generated php-fpm pool config for one major: the file `php_fpm_spec`
/// spawns against, and the file an uninstall removes.
///
/// `openvhost_conf::PhpFpmRuntime::generate_pool_config` derives the same path
/// independently (that crate cannot depend on this one), which is exactly the
/// drift this function's own test pins shut — see
/// `the_pool_config_path_matches_the_confs_independent_render`.
pub fn php_pool_config_path(home: &Path, major: &str) -> PathBuf {
    home.join("config/generated/php")
        .join(major)
        .join("php-fpm.conf")
}

pub fn php_fpm_spec(home: &Path, rt: &PhpRuntime) -> ServiceSpec {
    ensure_php_fpm_log_dir(home, &rt.major);
    ServiceSpec {
        id: php_fpm_service_id(&rt.major),
        display_name: format!("PHP-FPM {}", rt.major),
        endpoint: Some(format!("run/php-fpm-{}.sock", rt.major)),
        spawn: SpawnSpec {
            program: rt.fpm_bin.clone(),
            args: vec![
                OsString::from("-F"),
                OsString::from("-O"),
                OsString::from("-n"),
                OsString::from("-y"),
                php_pool_config_path(home, &rt.major).into_os_string(),
            ],
            cwd: None,
            env: vec![],
        },
        // Defaults only (openvhost-proc's per-service readiness probe + stop
        // grace, added for the MySQL lifecycle slice): today's behavior,
        // byte-for-byte unchanged.
        readiness: ReadinessProbe::default(),
        grace: DEFAULT_GRACE,
    }
}

/// Best-effort, log-don't-fail (mirrors `provision_home`'s own error
/// handling at every call site in this file, and `mysql_spec`'s
/// `ensure_custom_confd` below): a failure to create this directory must
/// never stop a `ServiceSpec` from being built and registered — the spec
/// itself is just data, and refusing to hand one back because of THIS side
/// effect would take away the honest `Failed` state a real spawn failure
/// already provides. `ensure_log_dir` is a no-op when the directory already
/// exists (at the right mode), so this costs nothing on the normal path.
///
/// Needed because php-fpm creates its `error_log` FILE but not the
/// directory containing it (P1 live-log-viewer design, spec D1/D2): this
/// function runs at cold-start registration and PHP-install/rescan time,
/// which can precede `openvhost_core::site::apply::commit` (the OTHER place
/// this same directory gets created, as part of an actual Apply) for a
/// freshly discovered major. That is also why this call site stays
/// standalone rather than folding away entirely once `ApplyPlan::log_dirs`
/// (spec D2's general mechanism) existed: a freshly discovered major can
/// have its `ServiceSpec` registered — and potentially started — before the
/// user ever runs an Apply, so `commit()` alone is not enough to guarantee
/// this directory exists in time.
///
/// What DOES fold here: directory creation now goes through
/// `openvhost_core::ensure_log_dir`, the SAME function `commit()` and
/// `provision_home` use, rather than a bare `create_dir_all` — so a PHP
/// major discovered mid-session gets its log directory at mode `0700`
/// (spec D5) exactly like one created by an Apply, instead of at whatever
/// the ambient umask would otherwise give it.
///
/// A `PhpVersion::parse` failure is swallowed the same best-effort way:
/// `major` is a raw probed string here, not yet validated, and a malformed
/// one must not stop the row from registering — it fails loudly later, at
/// spawn, exactly as it would have before this function existed.
fn ensure_php_fpm_log_dir(home: &Path, major: &str) {
    let Ok(major) = openvhost_core::PhpVersion::parse(major) else {
        return;
    };
    let error_log = openvhost_core::LogPaths::new(home).php_fpm_error(&major);
    let Some(dir) = error_log.parent() else {
        return; // structurally unreachable — see `LogPaths::php_fpm_error`
    };
    if let Err(e) = openvhost_core::ensure_log_dir(dir) {
        eprintln!(
            "php-fpm: failed to ensure the log directory {} exists: {e}",
            dir.display()
        );
    }
}

/// `ServiceSpec::grace` for every `mysql-<major>` row (P1 MySQL lifecycle
/// design, spec D4): SIGTERM is mysqld's documented clean-shutdown signal, and
/// a flushing InnoDB can legitimately exceed the 5s `DEFAULT_GRACE`
/// nginx/php-fpm use — a SIGKILL mid-flush then forces crash recovery on the
/// NEXT start. `pub(crate)`, not private: `quit.rs`'s quit-budget test
/// (`STOP_ALL_TIMEOUT` must outlive the longest registered grace) pins
/// against this constant rather than a bare literal `15`, so the two cannot
/// silently drift apart.
pub(crate) const MYSQL_GRACE: Duration = Duration::from_secs(15);

/// How long [`mysql_spec`]'s readiness probe (`mysqladmin ping`) may keep
/// retrying before the service is declared `Failed` (spec D4).
///
/// `pub(crate)`, not private (widened by the P1 CLI slice, same reasoning as
/// [`MYSQL_GRACE`] above): the control channel's per-service transition
/// deadline (`control::TRANSITION_TIMEOUT`) must outlive this probe PLUS the
/// grace that tears down a child which never became ready, and its test pins
/// against these constants rather than bare literals so the two cannot
/// silently drift apart.
pub(crate) const MYSQL_READY_DEADLINE: Duration = Duration::from_secs(15);

/// The `mysql-<major>` service row for one runtime: id, display name, TCP
/// endpoint, and the exact spawn + readiness spec (spec D4).
///
/// `endpoint` is `127.0.0.1:3306` — a literal, NOT this major's unix socket
/// path — deliberately unlike [`php_fpm_spec`]'s own `endpoint` (that pool's
/// socket): MySQL's socket is an internal implementation detail this app
/// uses for its own admin calls, but the address a HUMAN would actually
/// connect a `mysql` client or a GUI tool to is the TCP endpoint, so that is
/// what the Services panel row should show. The socket path itself is
/// surfaced separately, via `MysqlInstanceDto::socket_path` (`commands.rs`).
///
/// Argv is exactly `["--defaults-file=<my.cnf>"]` (spec D4: "`--defaults-file`
/// first is a mysqld requirement; everything else lives in the file so the
/// spec is stable") — built via `OsString`, not `format!` + `.display()`, for
/// the same non-lossy-path reason `MysqlValidator::validate` gives.
///
/// Post-live-run finding: also ensures `custom_confd` exists before
/// returning. A real mysqld aborts with "Fatal error in defaults handling.
/// Program aborted!" when the rendered my.cnf's `!includedir` names a
/// missing directory — `write_generated_config` (the my.cnf chokepoint)
/// guarantees this for a FRESH init, but every caller of `mysql_spec`
/// (`macos_stack`'s startup registration, `rescan_mysql_into_state`, and
/// `initialize_mysql`'s own post-init registration) builds a `ServiceSpec`
/// for an instance whose my.cnf was rendered at some point IN THE PAST —
/// possibly a past app version, possibly before the user deleted
/// `custom_confd` by hand. Nothing else re-renders/rewrites that my.cnf for
/// an already-`Initialized` datadir, so this is the one remaining place
/// that can repair the directory before the next supervised start.
pub fn mysql_spec(home: &Path, rt: &MysqlRuntime) -> ServiceSpec {
    let paths = mysql_paths(home, &rt.major);
    ensure_custom_confd(&paths.custom_confd);
    let mut defaults_file_arg = OsString::from("--defaults-file=");
    defaults_file_arg.push(paths.my_cnf.as_os_str());
    ServiceSpec {
        id: mysql_service_id(rt.major.as_str()),
        display_name: format!("MySQL {}", rt.major.as_str()),
        endpoint: Some("127.0.0.1:3306".to_string()),
        spawn: SpawnSpec {
            program: rt.mysqld.clone(),
            args: vec![defaults_file_arg],
            cwd: None,
            env: vec![],
        },
        readiness: ReadinessProbe::Command {
            argv: crate::mysql_admin::mysqladmin_ping_argv(&rt.mysqladmin, &paths.socket),
            deadline: MYSQL_READY_DEADLINE,
        },
        grace: MYSQL_GRACE,
    }
}

/// `ServiceSpec::grace` for the `mariadb-<series>` row. Deliberately an ALIAS
/// of [`MYSQL_GRACE`] rather than a second `Duration::from_secs(15)`: the
/// reason for the value is InnoDB's flush, which is a property of the storage
/// engine both servers share, and — more importantly — `quit.rs`'s
/// quit-budget test asserts `STOP_ALL_TIMEOUT` outlives [`MYSQL_GRACE`]. As
/// an alias that single assertion keeps covering the longest grace actually
/// registered; as an independent literal, raising one engine's grace past the
/// budget would sail past a test still watching the other's.
pub(crate) const MARIADB_GRACE: Duration = MYSQL_GRACE;

/// How long [`mariadb_spec`]'s readiness probe may retry — an alias of
/// [`MYSQL_READY_DEADLINE`] for the same reason [`MARIADB_GRACE`] is one:
/// `control::TRANSITION_TIMEOUT`'s test pins itself against that constant
/// plus the grace, and an alias keeps that budget honest for both engines
/// instead of only the one the assertion happens to name.
pub(crate) const MARIADB_READY_DEADLINE: Duration = MYSQL_READY_DEADLINE;

/// The TCP address the `mariadb-<series>` row advertises (spec D2).
///
/// **3307, and the fact that it is not 3306 is load-bearing**, in a way the
/// port number alone does not suggest. `tray::model::bulk_start_ids` collapses
/// services that share an endpoint STRING, on the correct assumption that two
/// services claiming one address are alternatives — which two MySQL majors
/// are, and two engines are not. A MariaDB row declaring `127.0.0.1:3306`
/// would therefore be dropped from "Start all" silently: no error, no log
/// line, just a service that never starts. Giving each engine its own address
/// is what lets both run at once, so this constant may not be changed to
/// match MySQL's without first changing that dedupe — and the dedupe is
/// right.
pub(crate) const MARIADB_ENDPOINT: &str = "127.0.0.1:3307";

/// The `mariadb-<series>` service row: id, display name, TCP endpoint, and
/// the exact spawn + readiness spec (spec D2/D5). The MariaDB counterpart of
/// [`mysql_spec`], sharing its shape and its reasoning:
///
/// - `endpoint` is the TCP address a human would point a client at, NOT this
///   instance's unix socket (which is an internal detail this app uses for
///   its own admin calls) — see [`MARIADB_ENDPOINT`] for why the value's
///   distinctness from MySQL's is what makes two engines coexist.
/// - argv is exactly `["--defaults-file=<my.cnf>"]`, built through `OsString`
///   rather than `format!` + `.display()` so a non-UTF-8 home is passed
///   through unchanged instead of lossily. Everything else lives in the file,
///   which keeps the spawn spec stable across every config change and keeps
///   the rendered config the single description of how the server is running.
/// - `program` is `rt.mariadbd`, which `openvhost-core`'s discovery has
///   already resolved to a CONCRETE version directory. It is not re-resolved
///   here and the `current` link is never spawned through: a later `current`
///   swap must not change which binary a restart brings up.
///
/// It also ensures two directories exist before handing the spec over, both
/// found by live runs rather than by unit tests, and both ensured HERE
/// because this function is the one chokepoint every registration path goes
/// through — startup today, and a rescan or a fresh init's own registration
/// once those exist. Neither can be left to init: init runs once, on a datadir
/// that did not exist yet, while these directories can be removed by hand at
/// any point afterwards, and nothing re-renders the config for an instance
/// already found `Initialized` on disk.
pub fn mariadb_spec(home: &Path, rt: &MariadbRuntime) -> ServiceSpec {
    let paths = mariadb_paths(home);
    ensure_custom_confd(&paths.custom_confd);
    ensure_run_dir(&paths.socket);
    let mut defaults_file_arg = OsString::from("--defaults-file=");
    defaults_file_arg.push(paths.my_cnf.as_os_str());
    ServiceSpec {
        id: mariadb_service_id(rt.series),
        display_name: format!("MariaDB {}", rt.series),
        endpoint: Some(MARIADB_ENDPOINT.to_string()),
        spawn: SpawnSpec {
            program: rt.mariadbd.clone(),
            args: vec![defaults_file_arg],
            cwd: None,
            env: vec![],
        },
        // Asserts that the server ANSWERS on its socket — never that a
        // credential works, which `ping` cannot tell us and which this probe
        // structurally must not try to: see `mariadb_admin_ping_argv`.
        readiness: ReadinessProbe::Command {
            argv: crate::mysql_admin::mariadb_admin_ping_argv(&rt.mariadb_admin, &paths.socket),
            deadline: MARIADB_READY_DEADLINE,
        },
        grace: MARIADB_GRACE,
    }
}

/// Best-effort, log-don't-fail (mirrors `provision_home`'s own error
/// handling at every call site in this file): a failure to create
/// `custom_confd` must never stop a `ServiceSpec` from being built and
/// registered — the spec itself is just data, and refusing to hand back a
/// spec because of THIS side effect would take away the honest `Failed`
/// state a real spawn failure already provides. `create_dir_all` is a no-op
/// when the directory already exists, so this costs nothing on the (normal,
/// expected) path where nothing was ever deleted.
///
/// Shared by both engines, and the message names no engine because the path
/// already does (`config/custom/<engine>/<series>/conf.d`) — a fixed `mysql:`
/// prefix would have been a small lie the day MariaDB started calling it.
fn ensure_custom_confd(custom_confd: &Path) {
    if let Err(e) = std::fs::create_dir_all(custom_confd) {
        eprintln!(
            "db: failed to ensure the custom conf.d directory {}: {e}",
            custom_confd.display()
        );
    }
}

/// Ensure `<home>/run` — the directory the server binds its socket in —
/// exists, best-effort and log-don't-fail exactly like [`ensure_custom_confd`]
/// above, and derived from the socket path rather than re-spelling `run` so
/// the writer and the reader cannot name different directories.
///
/// Found by Task 2's live gate, not by any unit test: a real `mariadbd` whose
/// run directory is missing reports `Bind on unix socket: No such file or
/// directory` and then the spectacularly misleading `Do you already have
/// another server running on socket …?`, which sends a reader hunting for a
/// phantom process. `initialize_mariadb` ensures the same directory for its
/// own temp server; that covers the init path only, and this is the
/// supervised-start half of the same requirement.
///
/// **Deliberately not added to [`mysql_spec`] in this slice.** Both engines
/// bind into `<home>/run` and both are covered on a normal launch, where
/// `provision_home` creates it before any spec is built. What differs is only
/// that MariaDB's failure text actively misleads, and MySQL's path is
/// live-proven as it stands — so the belt-and-braces goes where it was earned
/// rather than re-opening a proven path immediately before a gate. Extending
/// it to `mysql_spec` is a one-line follow-up, not a fix.
///
/// A plain `create_dir_all` matches `provision_home`'s own treatment of
/// `run` exactly (unlike `logs/`, which that function locks to `0700` through
/// `ensure_log_dir`), so this cannot leave the directory at a mode the normal
/// launch path would not have produced.
fn ensure_run_dir(socket: &Path) {
    let Some(run_dir) = socket.parent() else {
        return; // structurally unreachable — see `mariadb_paths`
    };
    if let Err(e) = std::fs::create_dir_all(run_dir) {
        eprintln!(
            "db: failed to ensure the run directory {} exists: {e}",
            run_dir.display()
        );
    }
}

/// Whether `rt`'s datadir is already initialized — the ONLY MySQL runtimes
/// `macos_stack`/a rescan register a supervisor row for at all (spec D6:
/// "registration reuses whatever nginx/php-fpm do at startup for
/// already-initialized instances"). An installed-but-not-yet-initialized
/// major has no datadir to serve, so there is nothing to start; a `Foreign`
/// one is rendered on the Databases page, never adopted into a service row.
/// Read from disk every time (never a stored boolean) — the same discipline
/// `classify_datadir` itself documents.
pub(crate) fn mysql_datadir_is_initialized(home: &Path, rt: &MysqlRuntime) -> bool {
    let paths = mysql_paths(home, &rt.major);
    matches!(
        classify_datadir(&paths.datadir),
        Ok(DatadirState::Initialized)
    )
}

/// Whether MariaDB's datadir is already initialized — the MariaDB half of
/// [`mysql_datadir_is_initialized`], and the same rule: only an initialized
/// instance gets a supervisor row, because there is nothing to start
/// otherwise. Read from disk every time, never a stored boolean.
///
/// Matched exhaustively rather than through `matches!` because
/// [`MariadbDatadirState::Foreign`] is a verdict a reader must see refused
/// here, not one that disappears into a wildcard: a datadir from another
/// series is a migration this build does not perform, and starting a server
/// against it would attempt one in place. A new variant must make this
/// function fail to compile.
#[cfg(target_os = "macos")]
pub(crate) fn mariadb_datadir_is_initialized(home: &Path) -> bool {
    match classify_mariadb_datadir(&mariadb_paths(home).datadir) {
        Ok(MariadbDatadirState::Initialized { .. }) => true,
        Ok(MariadbDatadirState::NotInitialized) | Ok(MariadbDatadirState::Foreign { .. }) => false,
        // A datadir this process cannot read is not one it may start.
        Err(_) => false,
    }
}

/// The multi-version PHP walk `macos_stack` performs at startup, factored out
/// of it so a test can hand it a fake prefix and a fake probe instead of the
/// machine's real Homebrew installs and a spawned `php-fpm -v`.
///
/// This is a thin pass-through to `openvhost_core::discover_php_in`, which
/// already has its own thorough test suite in
/// `openvhost-core/src/php/discover.rs` — so this function is NOT here to
/// re-test that walk's merge rules. It exists so the C2 regression test (see
/// the `tests` module below) pins that `macos_stack` calls the multi-version
/// walk at all, rather than only being able to exercise `discover_php_in`
/// again under a different name and never actually proving the startup path
/// was rewired to use it.
#[cfg(target_os = "macos")]
fn discover_installed_php(
    prefixes: &[&Path],
    probe: &dyn Fn(&Path) -> Option<String>,
) -> Vec<PhpRuntime> {
    // `.runtimes`: startup only needs what was positively identified.
    // `Discovery::unidentified` is reported by the rescan path, which is the
    // one a user can act on (`report_unidentified` in `commands.rs`).
    openvhost_core::discover_php_in(prefixes, probe).runtimes
}

/// The MySQL discovery walk `macos_stack` performs at startup, factored out
/// exactly like [`discover_installed_php`] and for the identical reason: a
/// test hands it a fake home and a fake probe instead of the machine's real
/// installs and a spawned `mysqld --version`. Thin pass-through to
/// `openvhost_core::mysql::discover_mysql`, which has its own thorough test
/// suite (`openvhost-core/src/mysql/discover.rs`) — its merge rules are not
/// re-tested here.
///
/// `home` is what makes OpenVHost's OWN package tree
/// (`<home>/packages/mysql/…`) visible to startup, alongside Homebrew (design
/// D3). The [`PackagesRoot`] is minted from the resolved home and from nothing
/// else. The tests below pin that this walk really reads that tree — a startup
/// that saw only half the machine is exactly the C2 defect
/// [`discover_installed_php`]'s comment records.
#[cfg(target_os = "macos")]
fn discover_installed_mysql(
    home: &Path,
    prefixes: &[&Path],
    probe: &dyn Fn(&Path) -> Option<String>,
) -> Vec<MysqlRuntime> {
    // `.runtimes` — see `discover_installed_php`.
    openvhost_core::mysql::discover_mysql(&PackagesRoot::from_home(home), prefixes, probe).runtimes
}

/// The MariaDB discovery walk `macos_stack` performs at startup, factored out
/// exactly like [`discover_installed_mysql`] so a test can hand it a fake home.
/// Thin pass-through to `openvhost_core::mariadb::discover_mariadb`, which has
/// its own thorough test suite — its rules are not re-tested here.
///
/// **No Homebrew prefixes and no version probe, and neither is an omission.**
/// MariaDB arrives only from OpenVHost's own package tree (the off-Homebrew
/// decision, 2026-08-01), so there is nothing outside `<home>/packages` to
/// look at; and the version is a directory name chosen at install time rather
/// than something to ask a binary for, so this walk spawns nothing at all —
/// unlike the PHP and MySQL walks above, which is why it needs no
/// `block_on` bridge.
#[cfg(target_os = "macos")]
fn discover_installed_mariadb(home: &Path) -> Vec<MariadbRuntime> {
    // `.runtimes` — see `discover_installed_php`.
    openvhost_core::mariadb::discover_mariadb(&PackagesRoot::from_home(home)).runtimes
}

/// Sweep abandoned MySQL staging directories (spec D2: "swept on rescan")
/// once at startup too, not only when the Databases page later triggers
/// `rescan_mysql_into_state` (`commands.rs`) — a crash or force-quit
/// mid-init otherwise leaves an `init-<major-dashed>-<uuid>` directory
/// sitting under `<home>/data/mysql` until a user happens to open that
/// page. Same log-don't-fail posture as `provision_home` immediately above
/// this call: a sweep failure must never block the supervisor from
/// starting.
#[cfg(target_os = "macos")]
fn sweep_stale_mysql_staging_at_startup(home: &Path) {
    if let Err(e) =
        openvhost_core::mysql::sweep_stale_staging(&openvhost_core::mysql::mysql_data_root(home))
    {
        eprintln!("stack: failed to sweep abandoned MySQL staging directories: {e}");
    }
}

/// Specs to register, the paths they were built from, and the runtimes probed
/// while building them. `paths` is `None` exactly when the home could not be
/// resolved — the same condition that already produces zero specs.
#[cfg(target_os = "macos")]
pub struct MacosStack {
    pub specs: Vec<ServiceSpec>,
    pub paths: Option<StackPaths>,
    pub runtimes: Option<InstalledRuntimes>,
    /// Every discovered MySQL runtime, regardless of whether its datadir is
    /// initialized (spec D6: the Databases page needs the FULL list to
    /// render `InstalledNotInitialized`/`DatadirForeign` rows, not just the
    /// ones that got a supervisor row in `specs`). `None` under the identical
    /// condition `runtimes`/`paths` are `None` under.
    pub mysql_runtimes: Option<Vec<MysqlRuntime>>,
}

/// Build the supervised stack rows: one nginx row, and one `php-fpm-<major>`
/// row per installed PHP major. Provision errors are logged and non-fatal
/// (rows register; Start surfaces the problem honestly). Only a
/// home-resolution failure skips the rows entirely — without a home there
/// are no config paths to point at.
///
/// The php-fpm version probe SPAWNS a process, so it happens exactly ONCE
/// here, at startup, and the result is handed out as managed
/// `Option<InstalledRuntimes>` state. That is what lets a later command
/// (site apply planning, called after every site mutation) stay process-free.
#[cfg(target_os = "macos")]
pub fn macos_stack() -> MacosStack {
    let home = match openvhost_core::resolve_home() {
        Ok(h) => h,
        Err(e) => {
            eprintln!("stack: cannot resolve OPENVHOST_HOME, skipping service rows: {e}");
            return MacosStack {
                specs: vec![],
                paths: None,
                runtimes: None,
                mysql_runtimes: None,
            };
        }
    };
    if let Err(e) = provision_home(&home) {
        eprintln!("stack: provisioning failed (rows registered anyway): {e}");
    }
    sweep_stale_mysql_staging_at_startup(&home);
    // nginx is unaffected by the C2 fix below: `find_brew_binaries` (or the
    // Apple Silicon fallback) is still what locates it.
    let brew = find_brew_binaries().unwrap_or_else(fallback_brew);

    // C2 fix (branch-review-fix-report.md): this used to probe ONLY
    // `brew.php_fpm` — the single path `find_brew_binaries` returns, which is
    // `None` unless BOTH nginx and an UNVERSIONED `php` formula share one
    // prefix. A machine with `php@8.1` and `php@8.3` installed but no bare
    // `php` formula made `find_brew_binaries` return `None`, so this fell back
    // to a path that does not exist on that machine, the probe found nothing,
    // and `php` ended up empty — Languages reported every catalogue version
    // as not installed and Sites disabled Save, on a machine with two working
    // PHP runtimes. `discover_php_in` is the multi-version walk the rest of
    // this slice (`rescan_php_runtimes`, `install_php`) already uses; it now
    // runs at startup too, so cold start and a live rescan see the same
    // runtimes through the same code, rather than startup alone using a
    // narrower single-binary probe.
    //
    // `discover_php_in` wants a SYNCHRONOUS probe closure, but
    // `openvhost_conf::probe_php_fpm_version` is async. `commands.rs`'s
    // `discover_all_php` (the rescan/install path) resolves that with
    // `spawn_blocking` + `Handle::block_on` because it runs INSIDE an async
    // Tauri command, on a tokio worker thread, where calling `block_on`
    // directly would panic. This function is different: it runs from
    // `lib.rs`'s `setup()` closure, which is plain synchronous code, not a
    // tokio worker — the single-probe version of this function already called
    // `tauri::async_runtime::block_on` directly below, proving that is safe
    // here. So the closure below does the same thing per candidate instead of
    // adding a `spawn_blocking` layer that this call site does not need.
    let prefixes: Vec<&Path> = openvhost_core::BREW_PREFIXES
        .iter()
        .map(Path::new)
        .collect();
    let php: Vec<PhpRuntime> = discover_installed_php(&prefixes, &|bin| {
        tauri::async_runtime::block_on(openvhost_conf::probe_php_fpm_version(bin))
    });

    // Same "spawn the version probe exactly once, at startup" discipline as
    // PHP above, and the identical sync-closure-over-async-probe bridge
    // (`tauri::async_runtime::block_on` is safe here because this whole
    // function runs from `lib.rs`'s synchronous `setup()` closure, never from
    // inside a tokio worker — see the PHP walk's own comment for why that
    // distinction matters).
    let mysql: Vec<MysqlRuntime> = discover_installed_mysql(&home, &prefixes, &|bin| {
        tauri::async_runtime::block_on(openvhost_conf::probe_mysqld_version(bin))
    });

    let nginx_conf = home.join("config/generated/nginx/nginx.conf");

    let mut specs = Vec::new();
    for rt in &php {
        specs.push(php_fpm_spec(&home, rt));
    }
    // Spec D6: "registration reuses whatever nginx/php-fpm do at startup for
    // ALREADY-INITIALIZED instances" — an installed-but-not-yet-initialized
    // major gets no row here (nothing to start yet); the Databases page
    // (Task 6) still lists it via `mysql_runtimes` below.
    for rt in &mysql {
        if mysql_datadir_is_initialized(&home, rt) {
            specs.push(mysql_spec(&home, rt));
        }
    }
    // The second engine, on the identical rule and ALONGSIDE MySQL rather
    // than instead of it (spec D2): the two carry different ids and
    // different endpoints precisely so both can be registered and both
    // started.
    //
    // The walk yields at most one runtime — this build ships exactly one
    // series — and the datadir check takes no runtime, because
    // `mariadb_paths` deliberately takes no series argument (its own doc
    // comment argues why). Discovery still runs first, so a machine that has
    // never installed MariaDB is never asked about a datadir; it spawns
    // nothing either way, costing a `read_link` and three `is_file` calls.
    for rt in discover_installed_mariadb(&home) {
        if mariadb_datadir_is_initialized(&home) {
            specs.push(mariadb_spec(&home, &rt));
        }
    }
    specs.push(ServiceSpec {
        id: "nginx".into(),
        display_name: "nginx".into(),
        endpoint: Some(format!("http://127.0.0.1:{LISTEN_PORT}")),
        spawn: SpawnSpec {
            program: brew.nginx.clone(),
            args: vec![
                OsString::from("-e"),
                openvhost_core::LogPaths::new(&home)
                    .nginx_error()
                    .into_os_string(),
                OsString::from("-c"),
                nginx_conf.clone().into_os_string(),
            ],
            cwd: None,
            env: vec![],
        },
        // Defaults only — see `php_fpm_spec`'s matching comment above.
        readiness: ReadinessProbe::default(),
        grace: DEFAULT_GRACE,
    });

    MacosStack {
        specs,
        paths: Some(StackPaths {
            home,
            nginx_bin: brew.nginx.clone(),
            nginx_conf,
        }),
        runtimes: Some(InstalledRuntimes {
            nginx_bin: brew.nginx,
            php,
        }),
        mysql_runtimes: Some(mysql),
    }
}

#[cfg(all(test, target_os = "macos"))]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;
    // Test-only: production code reaches the series through `rt.series` (the
    // value discovery actually recorded) and the package name through
    // `discover_mariadb`, never through the constants directly — which is
    // what keeps a spec describing the tree it was really found in.
    use openvhost_core::mariadb::{MARIADB_PACKAGE_NAME, MARIADB_SERIES};

    /// Post-live-run finding: a REAL mysqld aborts with "Fatal error in
    /// defaults handling. Program aborted!" when `!includedir` names a
    /// missing directory. `write_generated_config` (the my.cnf chokepoint)
    /// covers a FRESH init, but nothing re-renders my.cnf for an instance
    /// this app finds ALREADY initialized on disk — if the user deletes
    /// `custom_confd` after init, the very next supervised start would hit
    /// that fatal error with no code path left to repair it. `mysql_spec` is
    /// the one function every registration path (startup, rescan, a fresh
    /// init's own registration) builds a `ServiceSpec` through, so ensuring
    /// the directory here, before the spec is ever handed to the supervisor,
    /// closes that gap for all three callers at once.
    #[test]
    fn mysql_spec_ensures_the_custom_confd_directory_exists() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let home = tmp.path();
        let major = openvhost_core::mysql::MysqlMajor::parse("8.4").expect("valid major");
        let rt = MysqlRuntime {
            major: major.clone(),
            mysqld: PathBuf::from("/opt/homebrew/opt/mysql@8.4/bin/mysqld"),
            mysql: PathBuf::from("/opt/homebrew/opt/mysql@8.4/bin/mysql"),
            mysqladmin: PathBuf::from("/opt/homebrew/opt/mysql@8.4/bin/mysqladmin"),
            source: openvhost_core::mysql::MysqlRuntimeSource::Homebrew,
        };
        let custom_confd = mysql_paths(home, &major).custom_confd;
        assert!(
            !custom_confd.exists(),
            "must not exist before the call for this test to prove anything"
        );

        let _spec = mysql_spec(home, &rt);

        assert!(
            custom_confd.is_dir(),
            "mysql_spec must ensure the custom conf.d directory exists before its \
             ServiceSpec is ever handed to the supervisor"
        );
    }

    /// Mirrors `mysql_spec_ensures_the_custom_confd_directory_exists`.
    /// Without this, the P1 live-log-viewer bug fix (php-fpm's `error_log`
    /// moving to a per-major directory) means every existing install's
    /// php-fpm refuses to start the moment it ships:
    /// `openvhost_core::site::apply::commit` only creates this directory as
    /// part of an actual Apply, but `php_fpm_spec` also runs at cold-start
    /// registration and PHP-install/rescan time, which can precede any
    /// Apply for a freshly discovered major.
    #[test]
    fn php_fpm_spec_ensures_the_log_directory_exists() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let home = tmp.path();
        let rt = PhpRuntime {
            major: "8.4".to_string(),
            fpm_bin: PathBuf::from("/opt/homebrew/opt/php@8.4/sbin/php-fpm"),
        };
        let dir = openvhost_core::LogPaths::new(home)
            .php_fpm_error(&openvhost_core::PhpVersion::parse("8.4").expect("valid major"))
            .parent()
            .expect("php_fpm_error always has a parent")
            .to_path_buf();
        assert!(
            !dir.exists(),
            "must not exist before the call for this test to prove anything"
        );

        let _spec = php_fpm_spec(home, &rt);

        assert!(
            dir.is_dir(),
            "php_fpm_spec must ensure the log directory exists before its ServiceSpec is \
             ever handed to the supervisor"
        );
    }

    /// A PHP major discovered mid-session (Languages page install/rescan)
    /// gets its `ServiceSpec` — and therefore this directory — built through
    /// the SAME `ensure_php_fpm_log_dir` path a cold-start discovery does,
    /// before `site::apply::commit` (which mode-corrects at `0700` too, spec
    /// D5) ever runs for it. Both paths must agree, not merely both happen
    /// to "work".
    #[cfg(unix)]
    #[test]
    fn php_fpm_spec_creates_the_log_directory_at_mode_0700() {
        use std::os::unix::fs::PermissionsExt;

        let tmp = tempfile::tempdir().expect("tempdir");
        let home = tmp.path();
        let rt = PhpRuntime {
            major: "8.4".to_string(),
            fpm_bin: PathBuf::from("/opt/homebrew/opt/php@8.4/sbin/php-fpm"),
        };
        let dir = openvhost_core::LogPaths::new(home)
            .php_fpm_error(&openvhost_core::PhpVersion::parse("8.4").expect("valid major"))
            .parent()
            .expect("php_fpm_error always has a parent")
            .to_path_buf();

        let _spec = php_fpm_spec(home, &rt);

        let mode = std::fs::metadata(&dir)
            .expect("directory must exist")
            .permissions()
            .mode()
            & 0o777;
        assert_eq!(mode, 0o700, "got {mode:o}");
    }

    /// `php_pool_config_path` and `openvhost_conf`'s pool renderer derive the
    /// same path independently (that crate cannot depend on this one). If they
    /// drift, php-fpm is spawned against a file nothing ever wrote — and an
    /// uninstall deletes a file php-fpm never read. Both failures are silent,
    /// so pin them against each other through the REAL renderer.
    ///
    /// VACUITY (neuter-and-watch-it-fail): changed `php_pool_config_path` to
    /// join `"php-fpm.con"` — this test failed with the two paths differing;
    /// restoring it made it pass.
    #[test]
    fn the_pool_config_path_matches_the_confs_independent_render() {
        use openvhost_conf::{PhpRuntimeAdapter, PhpUpstream};

        let home = PathBuf::from("/tmp/ovh");
        let rendered = openvhost_conf::PhpFpmRuntime
            .generate_pool_config(
                &home,
                "8.4",
                &PhpUpstream::UnixSocket(home.join("run/php-fpm-8.4.sock")),
            )
            .expect("render must succeed")
            .expect("the unix path always yields a pool file");
        assert_eq!(rendered.path, php_pool_config_path(&home, "8.4"));
    }

    /// The id an uninstall/rescan strips a major back out of must be the id
    /// the spec registers. Asserted through the real `php_fpm_spec`/
    /// `mysql_spec`, not against a literal, so a change to either builder has
    /// to keep the prefix constants honest.
    #[test]
    fn service_ids_round_trip_through_their_prefixes() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let php = php_fpm_spec(
            tmp.path(),
            &PhpRuntime {
                major: "8.4".to_string(),
                fpm_bin: PathBuf::from("/opt/homebrew/opt/php@8.4/sbin/php-fpm"),
            },
        );
        // The literal, not just the round trip: a service id is a user-facing
        // argument (`openvhost start php-fpm-8.4`) and a tray row, so renaming
        // it is a breaking change that must be made on purpose. Deriving both
        // sides from one constant makes drift impossible but a RENAME silent,
        // which is what this line catches.
        assert_eq!(php.id, "php-fpm-8.4");
        assert_eq!(php.id.strip_prefix(PHP_FPM_ID_PREFIX), Some("8.4"));

        let major = openvhost_core::mysql::MysqlMajor::parse("8.4").expect("valid major");
        let mysql = mysql_spec(
            tmp.path(),
            &MysqlRuntime {
                major,
                mysqld: PathBuf::from("/opt/homebrew/opt/mysql@8.4/bin/mysqld"),
                mysql: PathBuf::from("/opt/homebrew/opt/mysql@8.4/bin/mysql"),
                mysqladmin: PathBuf::from("/opt/homebrew/opt/mysql@8.4/bin/mysqladmin"),
                source: openvhost_core::mysql::MysqlRuntimeSource::Homebrew,
            },
        );
        assert_eq!(mysql.id, "mysql-8.4");
        assert_eq!(mysql.id.strip_prefix(MYSQL_ID_PREFIX), Some("8.4"));
        // ...and the php prefix must NOT match a mysql row, or a PHP rescan
        // would happily unregister the database.
        assert_eq!(mysql.id.strip_prefix(PHP_FPM_ID_PREFIX), None);
    }

    /// The paths handed to the UI must be the SAME ones baked into the specs.
    /// A second `find_brew_binaries()` call could disagree with the first (it
    /// returns None unless BOTH nginx and php-fpm exist), so this pins that the
    /// page and the supervisor cannot drift.
    #[test]
    fn reported_paths_match_the_registered_nginx_spec() {
        let stack = macos_stack();
        let Some(paths) = stack.paths else {
            // No home resolvable in this environment: the specs must be empty
            // too, which is the existing contract.
            assert!(stack.specs.is_empty());
            return;
        };
        let nginx = stack
            .specs
            .iter()
            .find(|s| s.id == "nginx")
            .expect("nginx spec should be registered when a home resolves");
        assert_eq!(nginx.spawn.program, paths.nginx_bin);
        // The spec spawns with `-c <conf>`; the reported conf must be that path.
        let args: Vec<String> = nginx
            .spawn
            .args
            .iter()
            .map(|a| a.to_string_lossy().into_owned())
            .collect();
        let c = args
            .iter()
            .position(|a| a == "-c")
            .expect("nginx spawns with -c");
        assert_eq!(args[c + 1], paths.nginx_conf.to_string_lossy());
    }

    /// C2 (branch-review-fix-report.md): the exact machine shape that used to
    /// report zero PHP runtimes at startup — `php@8.1` and `php@8.3` both
    /// installed, but no UNVERSIONED `php` formula for `find_brew_binaries` to
    /// pair with nginx. Before this fix, `macos_stack` probed only the single
    /// `find_brew_binaries().php_fpm` path (or its Apple-Silicon fallback,
    /// which does not exist on this machine either), so it found nothing and
    /// `php` came back empty. Pin that the startup discovery now finds BOTH
    /// majors — with no unversioned `php` alias present at all.
    #[test]
    fn startup_discovery_finds_multiple_majors_without_an_unversioned_php_formula() {
        let dir = tempfile::tempdir().expect("tempdir");
        for formula in ["php@8.1", "php@8.3"] {
            let bin = dir.path().join("opt").join(formula).join("sbin/php-fpm");
            std::fs::create_dir_all(bin.parent().expect("parent")).expect("mkdir");
            std::fs::write(&bin, b"#!/bin/sh\n").expect("write fake php-fpm");
        }
        // No "opt/php" directory anywhere: the unversioned alias
        // `find_brew_binaries` requires is genuinely absent.
        assert!(!dir.path().join("opt/php").exists());

        let probe = |bin: &Path| -> Option<String> {
            let s = bin.to_string_lossy();
            if s.contains("php@8.1") {
                Some("8.1".to_string())
            } else if s.contains("php@8.3") {
                Some("8.3".to_string())
            } else {
                None
            }
        };

        let found = discover_installed_php(&[dir.path()], &probe);
        let majors: Vec<&str> = found.iter().map(|r| r.major.as_str()).collect();
        assert_eq!(majors, vec!["8.1", "8.3"], "got {found:?}");
    }

    /// Review fix wave, minor 3: a crash or force-quit mid-init leaves an
    /// `init-<major-dashed>-<uuid>` staging directory behind, and before
    /// this fix nothing swept it until a user happened to open the
    /// Databases page (which triggers `rescan_mysql_into_state`, the only
    /// existing call site). `sweep_stale_mysql_staging_at_startup` is
    /// exercised directly here — not through `macos_stack()` itself, which
    /// resolves the REAL `OPENVHOST_HOME` internally and has no injectable
    /// home parameter, so driving it from a test would mean mutating
    /// process-wide env or touching the actual user's home directory.
    #[test]
    fn sweep_stale_mysql_staging_at_startup_removes_an_abandoned_staging_dir() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let home = tmp.path();
        let staging =
            openvhost_core::mysql::mysql_data_root(home).join("init-8-4-deadbeef00000000");
        std::fs::create_dir_all(&staging).expect("create staging dir");

        sweep_stale_mysql_staging_at_startup(home);

        assert!(
            !staging.exists(),
            "an abandoned staging directory must be swept at startup, not only on a later rescan"
        );
    }

    // ------------------------------------------------------------------
    // MySQL-from-tarball design D3/D5 — the seam between discovery and the
    // spec the supervisor actually spawns.
    //
    // `openvhost-core` owns the merge rules and tests them thoroughly. What
    // is provable ONLY here is that startup reads the packaged tree at all,
    // and that the concrete path core resolved survives into
    // `ServiceSpec::spawn.program` — the value a child is really spawned
    // from.
    // ------------------------------------------------------------------

    /// Lay down `<home>/packages/mysql/<major>/<version>/bin/{mysqld,mysql,
    /// mysqladmin}` with `mysqld`'s body set to `body`, exactly as an install
    /// leaves it — so a test can tell one version's binary from another's by
    /// CONTENT rather than by the path it was reached through.
    #[cfg(unix)]
    fn install_fake_mysql_package(home: &Path, major: &str, version: &str, body: &str) {
        let bin = PackagesRoot::from_home(home)
            .package_dir("mysql", major, version)
            .join("bin");
        std::fs::create_dir_all(&bin).expect("mkdir package bin");
        for name in ["mysqld", "mysql", "mysqladmin"] {
            let content = if name == "mysqld" {
                body
            } else {
                "#!/bin/sh\n"
            };
            std::fs::write(bin.join(name), content.as_bytes()).expect("write fake binary");
        }
    }

    /// Point (or re-point) `packages/<package>/<major>/current` at `target`,
    /// the way `openvhost-pkg` does: a RELATIVE symlink naming the bare
    /// version. Takes the package name because both engines' trees are laid
    /// out identically — only the segment naming the engine differs — and a
    /// second copy of this helper is how one engine's tests end up asserting
    /// against a link shape the other's writer no longer produces.
    #[cfg(unix)]
    fn point_current(home: &Path, package: &str, major: &str, target: &str) {
        let link = PackagesRoot::from_home(home).current_link(package, major);
        std::fs::create_dir_all(link.parent().expect("major dir")).expect("mkdir major");
        let _ = std::fs::remove_file(&link);
        std::os::unix::fs::symlink(PathBuf::from(target), &link).expect("symlink current");
    }

    /// D3, at the startup seam: `macos_stack`'s MySQL walk must see OpenVHost's
    /// OWN package tree, not just Homebrew. Deliberately run with NO brew
    /// prefixes and a probe that panics if consulted — so the only way this can
    /// pass is by reading `<home>/packages/`, and it cannot pass by falling
    /// through to a keg on the machine running the test.
    #[cfg(unix)]
    #[test]
    fn startup_discovery_finds_a_packaged_mysql_with_no_homebrew_at_all() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let home = tmp.path();
        install_fake_mysql_package(home, "8.4", "8.4.11", "8.4.11 server\n");
        point_current(home, "mysql", "8.4", "8.4.11");

        let found = discover_installed_mysql(home, &[], &|_| {
            panic!("startup must not probe a packaged runtime for its version")
        });
        assert_eq!(found.len(), 1, "got {found:?}");
        assert_eq!(found[0].major.as_str(), "8.4");
        assert_eq!(
            found[0].source,
            openvhost_core::mysql::MysqlRuntimeSource::Packaged {
                version: "8.4.11".to_string()
            },
            "the row must be able to say where it came from"
        );
    }

    /// D5, at the seam that matters: the path a supervised child is spawned
    /// from is the concrete version directory, and a later `current` swap does
    /// not reach back and change which engine a restart brings up.
    ///
    /// Asserting only that the path *looks* concrete would pass against a
    /// `current` link that happens to resolve, so the swap is the load-bearing
    /// half. The registered `ServiceSpec` is the record: `openvhost-proc`
    /// spawns `spawn.program` verbatim, and a re-`Start` re-uses the stored
    /// spec.
    ///
    /// VACUITY, proven by mutation: rewriting `packaged_mysql_runtime` in
    /// `openvhost-core` to build its paths from `root.current_link(...)`
    /// instead of `root.package_dir(...)` fails this test. Re-running with the
    /// two shape assertions neutered leaves the swap assertion still failing,
    /// `left: "8.4.10 server\n"` — so the swap, not the shape, is what pins
    /// D5 here.
    #[cfg(unix)]
    #[test]
    fn a_packaged_mysql_spec_spawns_a_concrete_version_and_survives_a_current_swap() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let home = tmp.path();
        install_fake_mysql_package(home, "8.4", "8.4.10", "8.4.10 server\n");
        install_fake_mysql_package(home, "8.4", "8.4.11", "8.4.11 server\n");
        point_current(home, "mysql", "8.4", "8.4.11");

        let found = discover_installed_mysql(home, &[], &|_| None);
        assert_eq!(found.len(), 1, "got {found:?}");
        let spec = mysql_spec(home, &found[0]);

        assert!(
            spec.spawn
                .program
                .starts_with(PackagesRoot::from_home(home).package_dir("mysql", "8.4", "8.4.11")),
            "the supervisor would spawn {:?}, which is not the concrete version directory",
            spec.spawn.program
        );
        assert!(
            !spec
                .spawn
                .program
                .components()
                .any(|c| c.as_os_str() == "current"),
            "the supervisor would spawn through the current link: {:?}",
            spec.spawn.program
        );

        // A `current` swap is a legitimate operation (a future upgrade flow
        // does exactly this). It must not silently change which binary the
        // already-registered spec starts.
        point_current(home, "mysql", "8.4", "8.4.10");
        assert_eq!(
            std::fs::read(&spec.spawn.program).expect("read the spawned binary"),
            b"8.4.11 server\n",
            "a current swap changed the engine an already-registered spec spawns"
        );
    }

    // ------------------------------------------------------------------
    // MariaDB: the SECOND engine's supervisor row (spec D2/D5).
    //
    // Discovery itself is `openvhost-core`'s and is tested thoroughly
    // there. What is provable ONLY here is the shape of the row the
    // Supervisor is actually handed — the argv it spawns, the binary that
    // argv names, and the id/endpoint pair that decides whether this row
    // and MySQL's can coexist at all.
    // ------------------------------------------------------------------

    /// Lay down `<home>/packages/mariadb/11.4/<version>/bin/{mariadbd,
    /// mariadb,mariadb-admin}` with `mariadbd`'s body set to `body` — the
    /// counterpart of [`install_fake_mysql_package`], separate rather than
    /// generic because the three binary NAMES are precisely what differs
    /// between the two engines (`openvhost-core`'s own discovery module
    /// makes the same call, for the same reason).
    #[cfg(unix)]
    fn install_fake_mariadb_package(home: &Path, version: &str, body: &str) {
        let bin = PackagesRoot::from_home(home)
            .package_dir(MARIADB_PACKAGE_NAME, MARIADB_SERIES, version)
            .join("bin");
        std::fs::create_dir_all(&bin).expect("mkdir package bin");
        for name in ["mariadbd", "mariadb", "mariadb-admin"] {
            let content = if name == "mariadbd" {
                body
            } else {
                "#!/bin/sh\n"
            };
            std::fs::write(bin.join(name), content.as_bytes()).expect("write fake binary");
        }
    }

    /// A runtime pointing at paths that need not exist: every test below
    /// except the packaged-discovery one is about the SPEC's shape, and a
    /// `ServiceSpec` is data — it is built without touching either binary.
    fn fake_mariadb_runtime() -> MariadbRuntime {
        MariadbRuntime {
            series: MARIADB_SERIES,
            version: "11.4.9".to_string(),
            mariadbd: PathBuf::from("/nowhere/11.4.9/bin/mariadbd"),
            mariadb: PathBuf::from("/nowhere/11.4.9/bin/mariadb"),
            mariadb_admin: PathBuf::from("/nowhere/11.4.9/bin/mariadb-admin"),
        }
    }

    /// Limited to CATALOGUE majors: `MysqlMajor::from_probe` (the shape-only
    /// constructor discovery uses) is `pub(crate)` to `openvhost-core`, so a
    /// non-catalogue major cannot be built from this crate at all. That is
    /// why the id-collision test below works on
    /// [`mysql_service_id`]/[`mariadb_service_id`] directly rather than on
    /// runtimes — the id functions accept any probed major, which is exactly
    /// the population "distinct from every MySQL major" has to cover, and
    /// `11.4` (the interesting one) is not in the catalogue.
    fn fake_mysql_runtime(major: &str) -> MysqlRuntime {
        let major = openvhost_core::mysql::MysqlMajor::parse(major).expect("a catalogue major");
        MysqlRuntime {
            major,
            mysqld: PathBuf::from("/nowhere/bin/mysqld"),
            mysql: PathBuf::from("/nowhere/bin/mysql"),
            mysqladmin: PathBuf::from("/nowhere/bin/mysqladmin"),
            source: openvhost_core::mysql::MysqlRuntimeSource::Homebrew,
        }
    }

    /// The `ServiceStatus` the tray sees for a freshly registered, not-yet-
    /// started row — built FROM the real `ServiceSpec` rather than from
    /// hand-typed strings, so a test cannot pass against an id or endpoint
    /// the Supervisor was never actually given.
    fn stopped_row(spec: &ServiceSpec) -> openvhost_proc::ServiceStatus {
        openvhost_proc::ServiceStatus {
            id: spec.id.clone(),
            display_name: spec.display_name.clone(),
            endpoint: spec.endpoint.clone(),
            pid: None,
            state: openvhost_proc::ServiceState::Stopped,
        }
    }

    // ---- Group A: argv is EXACTLY one argument ----

    /// Spec D4's rule, carried to the second engine: `--defaults-file` is a
    /// server requirement and everything else lives inside that file, so the
    /// spawn spec is stable across every config change. A second argument
    /// here would mean a setting that the rendered my.cnf does not describe
    /// — invisible to the diff preview and to `mariadbd --verbose --help`.
    #[test]
    fn the_mariadb_spec_argv_is_exactly_one_defaults_file_argument() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let home = tmp.path();

        let spec = mariadb_spec(home, &fake_mariadb_runtime());

        let mut expected = OsString::from("--defaults-file=");
        expected.push(mariadb_paths(home).my_cnf.as_os_str());
        assert_eq!(
            spec.spawn.args,
            vec![expected],
            "argv must be exactly one --defaults-file argument, got {:?}",
            spec.spawn.args
        );
        assert!(
            spec.spawn.env.is_empty() && spec.spawn.cwd.is_none(),
            "nothing may reach the server outside the defaults file: {:?}",
            spec.spawn
        );
    }

    // ---- Group B: a CONCRETE program path, never `current` ----

    /// The lesson that cost a full misdiagnosis in the MySQL slice (spec
    /// D5), re-proven at the seam that matters: the Supervisor spawns
    /// `ServiceSpec::spawn.program`, so if that path went through the
    /// `current` link, swinging the link would silently change which engine
    /// a restart brings up while the UI still described the old one.
    ///
    /// Non-vacuous by CONTENT, not by path shape: the final assertion reads
    /// the bytes back through the recorded path after the swap. Had the spec
    /// recorded `…/current/bin/mariadbd`, that identical read would return
    /// the other version's bytes.
    #[cfg(unix)]
    #[test]
    fn a_packaged_mariadb_spec_spawns_a_concrete_version_and_survives_a_current_swap() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let home = tmp.path();
        install_fake_mariadb_package(home, "11.4.9", "11.4.9 server\n");
        install_fake_mariadb_package(home, "11.4.10", "11.4.10 server\n");
        point_current(home, MARIADB_PACKAGE_NAME, MARIADB_SERIES, "11.4.10");

        let found = discover_installed_mariadb(home);
        assert_eq!(found.len(), 1, "got {found:?}");
        let spec = mariadb_spec(home, &found[0]);

        assert!(
            spec.spawn
                .program
                .starts_with(PackagesRoot::from_home(home).package_dir(
                    MARIADB_PACKAGE_NAME,
                    MARIADB_SERIES,
                    "11.4.10"
                )),
            "the supervisor would spawn {:?}, which is not the concrete version directory",
            spec.spawn.program
        );
        assert!(
            !spec
                .spawn
                .program
                .components()
                .any(|c| c.as_os_str() == "current"),
            "the supervisor would spawn through the current link: {:?}",
            spec.spawn.program
        );

        point_current(home, MARIADB_PACKAGE_NAME, MARIADB_SERIES, "11.4.9");
        assert_eq!(
            std::fs::read(&spec.spawn.program).expect("read the spawned binary"),
            b"11.4.10 server\n",
            "a current swap changed the engine an already-registered spec spawns"
        );
        // And the swap really did take effect — otherwise the assertion above
        // could be passing because nothing moved at all.
        let after = mariadb_spec(home, &discover_installed_mariadb(home)[0]);
        assert_eq!(
            std::fs::read(&after.spawn.program).expect("read the spawned binary"),
            b"11.4.9 server\n",
        );
    }

    // ---- Group C: id and endpoint distinct from EVERY MySQL major ----

    /// Two MySQL majors are alternatives for one address; two ENGINES are
    /// not. `11.4` is in the list deliberately: it is the one probed MySQL
    /// major whose bare version string equals MariaDB's series, so an id
    /// built without an engine-naming prefix would collide there and
    /// nowhere else.
    #[test]
    fn the_mariadb_id_collides_with_no_mysql_major_including_its_own_series_string() {
        let mariadb = mariadb_service_id(MARIADB_SERIES);
        for major in ["5.7", "8.0", "8.4", "9.0", MARIADB_SERIES] {
            assert_ne!(mariadb, mysql_service_id(major), "major {major}");
        }
        assert!(
            mariadb.starts_with(MARIADB_ID_PREFIX) && !mariadb.starts_with(MYSQL_ID_PREFIX),
            "{mariadb} is not recognisable as a MariaDB row"
        );
    }

    /// Spec D2, at the value that actually reaches the tray: the two rows'
    /// endpoints, read off real specs rather than off the constants.
    #[test]
    fn the_two_engines_declare_different_endpoints() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let home = tmp.path();

        let my = mysql_spec(home, &fake_mysql_runtime("8.4"));
        let mdb = mariadb_spec(home, &fake_mariadb_runtime());

        assert_eq!(my.endpoint.as_deref(), Some("127.0.0.1:3306"));
        assert_eq!(mdb.endpoint.as_deref(), Some("127.0.0.1:3307"));
        assert_ne!(my.endpoint, mdb.endpoint);
        assert_ne!(my.id, mdb.id);
    }

    // ---- Group D: BOTH engines are started by "Start all" ----

    /// The regression spec D2 exists to prevent, pinned at the only place it
    /// is observable. `tray::model::bulk_start_ids` collapses services that
    /// share an endpoint STRING, correctly treating them as alternatives for
    /// one address — so a MariaDB row declaring `127.0.0.1:3306` would be
    /// dropped from "Start all" with **no error and no log line**: a service
    /// that simply never starts.
    ///
    /// Non-vacuity is the whole point of the second half of this test. The
    /// first half alone would keep passing if the dedupe were deleted
    /// outright; the second half re-runs the identical pair with MariaDB
    /// declaring MySQL's address and shows the row really does vanish. So
    /// the first assertion passes BECAUSE of the distinct endpoint, and not
    /// for want of a mechanism that could drop it.
    #[test]
    fn both_engines_survive_the_trays_endpoint_dedupe_and_start_together() {
        use crate::tray::model::bulk_start_ids;

        let tmp = tempfile::tempdir().expect("tempdir");
        let home = tmp.path();
        let my = mysql_spec(home, &fake_mysql_runtime("8.4"));
        let mdb = mariadb_spec(home, &fake_mariadb_runtime());

        let ids = bulk_start_ids(&[stopped_row(&my), stopped_row(&mdb)]);
        assert!(
            ids.contains(&my.id) && ids.contains(&mdb.id),
            "Start all must start both engines, got {ids:?}"
        );

        let collided = openvhost_proc::ServiceStatus {
            endpoint: my.endpoint.clone(),
            ..stopped_row(&mdb)
        };
        let ids = bulk_start_ids(&[stopped_row(&my), collided]);
        assert_eq!(
            ids,
            vec![my.id.clone()],
            "the dedupe that the distinct endpoint exists to escape is not actually live, \
             so the assertion above proves nothing"
        );
    }

    // ---- Group E: the directories a real server aborts without ----

    /// Both found by a live run, not by a unit test, and both repaired at
    /// the one chokepoint every registration path goes through — see
    /// `mariadb_spec`'s own doc comment for why the spec, and not init, is
    /// where this belongs.
    #[test]
    fn mariadb_spec_ensures_the_directories_a_real_server_aborts_without() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let home = tmp.path();
        let paths = mariadb_paths(home);
        let run_dir = paths.socket.parent().expect("the socket has a parent");
        assert!(
            !paths.custom_confd.exists() && !run_dir.exists(),
            "neither may exist before the call, or this test proves nothing"
        );

        let _spec = mariadb_spec(home, &fake_mariadb_runtime());

        assert!(
            paths.custom_confd.is_dir(),
            "a missing !includedir aborts defaults handling"
        );
        assert!(
            run_dir.is_dir(),
            "a missing run directory makes mariadbd report a phantom other server"
        );
    }

    // ---- Group F: readiness ----

    /// The probe asserts the server ANSWERS, never that a credential works —
    /// see `mariadb_spec` and `mariadb_admin_ping_argv`. What is pinned here
    /// is that the probe is a real command bounded by a deadline (a default
    /// `AliveAfter` probe would call a server `Running` while it was still
    /// building its redo logs) and that no credential rides along in it.
    #[test]
    fn the_readiness_probe_is_a_bounded_ping_carrying_no_credential() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let home = tmp.path();
        let rt = fake_mariadb_runtime();

        let spec = mariadb_spec(home, &rt);

        match &spec.readiness {
            ReadinessProbe::Command { argv, deadline } => {
                assert_eq!(*deadline, MARIADB_READY_DEADLINE);
                assert_eq!(
                    argv.first().map(String::as_str),
                    Some("/nowhere/11.4.9/bin/mariadb-admin")
                );
                assert!(argv.iter().any(|a| a == "ping"), "{argv:?}");
                assert!(
                    argv.iter().all(|a| !a.contains("password")),
                    "a credential must never reach argv: {argv:?}"
                );
            }
            other => panic!("expected a Command probe, got {other:?}"),
        }
        assert!(
            spec.grace >= MYSQL_GRACE,
            "InnoDB needs at least what MySQL's flush budget allows"
        );
    }
}
