// SPDX-License-Identifier: GPL-3.0-or-later
//! The stack paths the app reports, plus macOS service registration.
//! `StackPaths` is a portable data type defined for every target; only building
//! it is platform-specific. Data-only: binaries from the Homebrew probe
//! (resolved at registration time), configs generated by `site::apply` under
//! `<home>/config/generated/`. The generated tree is the ONLY config source —
//! see `openvhost_core::platform::macos::demo_stack::provision_home`, which
//! creates directories and seeds the welcome page but writes no config.

use std::ffi::OsString;
use std::path::{Path, PathBuf};

#[cfg(target_os = "macos")]
use openvhost_core::platform::macos::demo_stack::{BrewStack, find_brew_binaries, provision_home};
#[cfg(target_os = "macos")]
use openvhost_core::site::apply::LISTEN_PORT;
// Portable: `InstalledRuntimes`/`PhpRuntime` are plain data (see `StackPaths`'s
// own doc comment for why portable types are named ungated even though only
// `macos_stack` constructs them today), and `php_fpm_spec` below is called
// from `commands.rs`, which is ungated too.
use openvhost_core::{InstalledRuntimes, PhpRuntime};
use openvhost_proc::{ServiceSpec, SpawnSpec};

/// Apple Silicon default paths, used when probing finds nothing: the rows
/// still register, and Start yields an honest Failed naming the missing
/// path (the P0-3 spawn-fail contract) instead of the rows vanishing.
#[cfg(target_os = "macos")]
fn fallback_brew() -> BrewStack {
    BrewStack {
        nginx: PathBuf::from("/opt/homebrew/opt/nginx/bin/nginx"),
        php_fpm: PathBuf::from("/opt/homebrew/opt/php/sbin/php-fpm"),
    }
}

/// The paths the stack actually registered, so the Web Server page can report
/// them instead of re-probing and possibly disagreeing. Read out of the managed
/// `Option<StackPaths>` state by `commands::list_web_servers` and friends.
///
/// Portable by construction — three `PathBuf`s, nothing platform-specific — so
/// it is defined for EVERY target and `commands.rs` can name it ungated. Only
/// building one is platform-specific (`macos_stack` below); targets with no
/// stack builder manage `None`.
// On a target with no stack builder this type is named and its fields are read
// by ungated `commands.rs` code, but nothing CONSTRUCTS it, which is rustc's
// separate "struct is never constructed" dead_code diagnostic. Reproduced in
// isolation on rustc 1.96: that diagnostic does NOT fire for a struct whose
// fields are read from a reachable signature, so this allow is belt-and-braces
// rather than load-bearing. Kept because no non-macOS target can be compiled
// from this repo yet (libsqlite3-sys's bundled C blocks cross-checks) and the
// diagnostic's exact trigger has moved between releases, while the cost is nil:
// it is cfg'd OFF on macOS, where all three fields are genuinely read, so no
// dead-code signal is suppressed on the platform actually built here. Do NOT
// switch this to `#[expect]` — that warns when the lint does not fire, turning
// the unverifiable direction into a guaranteed break. A `#[cfg(not(macos))]`
// duplicate stub type is also not the answer: unverifiable code that drifts.
#[cfg_attr(not(target_os = "macos"), allow(dead_code))]
pub struct StackPaths {
    pub home: PathBuf,
    pub nginx_bin: PathBuf,
    pub nginx_conf: PathBuf,
}

/// The `php-fpm-<major>` service row for one runtime: id, display name,
/// endpoint (the pool's own socket) and the exact spawn spec.
///
/// Extracted so `macos_stack` (built once at startup) and the desktop crate's
/// PHP rescan/install commands (which register a row for a version installed
/// AFTER launch) build the row identically. Two independent copies of this
/// spec drifting apart would mean an installed-after-launch version serves
/// through a subtly different pool than one present at launch — a silent
/// correctness gap, not a crash, so nothing would fail loudly enough to catch
/// it.
///
/// Portable data construction — like `StackPaths`, only building the STACK
/// (`macos_stack`) is platform-specific today; this row-shape function is
/// not.
pub fn php_fpm_spec(home: &Path, rt: &PhpRuntime) -> ServiceSpec {
    ServiceSpec {
        id: format!("php-fpm-{}", rt.major),
        display_name: format!("PHP-FPM {}", rt.major),
        endpoint: Some(format!("run/php-fpm-{}.sock", rt.major)),
        spawn: SpawnSpec {
            program: rt.fpm_bin.clone(),
            args: vec![
                OsString::from("-F"),
                OsString::from("-O"),
                OsString::from("-n"),
                OsString::from("-y"),
                home.join(format!("config/generated/php/{}/php-fpm.conf", rt.major))
                    .into_os_string(),
            ],
            cwd: None,
            env: vec![],
        },
    }
}

/// Specs to register, the paths they were built from, and the runtimes probed
/// while building them. `paths` is `None` exactly when the home could not be
/// resolved — the same condition that already produces zero specs.
#[cfg(target_os = "macos")]
pub struct MacosStack {
    pub specs: Vec<ServiceSpec>,
    pub paths: Option<StackPaths>,
    pub runtimes: Option<InstalledRuntimes>,
}

/// Build the supervised stack rows: one nginx row, and one `php-fpm-<major>`
/// row per installed PHP major. Provision errors are logged and non-fatal
/// (rows register; Start surfaces the problem honestly). Only a
/// home-resolution failure skips the rows entirely — without a home there
/// are no config paths to point at.
///
/// The php-fpm version probe SPAWNS a process, so it happens exactly ONCE
/// here, at startup, and the result is handed out as managed
/// `Option<InstalledRuntimes>` state. That is what lets a later command
/// (site apply planning, called after every site mutation) stay process-free.
#[cfg(target_os = "macos")]
pub fn macos_stack() -> MacosStack {
    let home = match openvhost_core::resolve_home() {
        Ok(h) => h,
        Err(e) => {
            eprintln!("stack: cannot resolve OPENVHOST_HOME, skipping service rows: {e}");
            return MacosStack {
                specs: vec![],
                paths: None,
                runtimes: None,
            };
        }
    };
    if let Err(e) = provision_home(&home) {
        eprintln!("stack: provisioning failed (rows registered anyway): {e}");
    }
    let brew = find_brew_binaries().unwrap_or_else(fallback_brew);

    // Probing spawns a process, so it happens ONCE here and the result is
    // managed state. That is what lets `plan_site_apply` stay process-free.
    let major =
        tauri::async_runtime::block_on(openvhost_conf::probe_php_fpm_version(&brew.php_fpm));

    let nginx_conf = home.join("config/generated/nginx/nginx.conf");
    let php: Vec<PhpRuntime> = major
        .iter()
        .map(|m| PhpRuntime {
            major: m.clone(),
            fpm_bin: brew.php_fpm.clone(),
        })
        .collect();

    let mut specs = Vec::new();
    for rt in &php {
        specs.push(php_fpm_spec(&home, rt));
    }
    specs.push(ServiceSpec {
        id: "nginx".into(),
        display_name: "nginx".into(),
        endpoint: Some(format!("http://127.0.0.1:{LISTEN_PORT}")),
        spawn: SpawnSpec {
            program: brew.nginx.clone(),
            args: vec![
                OsString::from("-e"),
                home.join("logs/nginx.error.log").into_os_string(),
                OsString::from("-c"),
                nginx_conf.clone().into_os_string(),
            ],
            cwd: None,
            env: vec![],
        },
    });

    MacosStack {
        specs,
        paths: Some(StackPaths {
            home,
            nginx_bin: brew.nginx.clone(),
            nginx_conf,
        }),
        runtimes: Some(InstalledRuntimes {
            nginx_bin: brew.nginx,
            php,
        }),
    }
}

#[cfg(all(test, target_os = "macos"))]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    /// The paths handed to the UI must be the SAME ones baked into the specs.
    /// A second `find_brew_binaries()` call could disagree with the first (it
    /// returns None unless BOTH nginx and php-fpm exist), so this pins that the
    /// page and the supervisor cannot drift.
    #[test]
    fn reported_paths_match_the_registered_nginx_spec() {
        let stack = macos_stack();
        let Some(paths) = stack.paths else {
            // No home resolvable in this environment: the specs must be empty
            // too, which is the existing contract.
            assert!(stack.specs.is_empty());
            return;
        };
        let nginx = stack
            .specs
            .iter()
            .find(|s| s.id == "nginx")
            .expect("nginx spec should be registered when a home resolves");
        assert_eq!(nginx.spawn.program, paths.nginx_bin);
        // The spec spawns with `-c <conf>`; the reported conf must be that path.
        let args: Vec<String> = nginx
            .spawn
            .args
            .iter()
            .map(|a| a.to_string_lossy().into_owned())
            .collect();
        let c = args
            .iter()
            .position(|a| a == "-c")
            .expect("nginx spawns with -c");
        assert_eq!(args[c + 1], paths.nginx_conf.to_string_lossy());
    }
}
