// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	coreInfo: (simulateError: boolean | null) => typedError<CoreInfo, IpcError>(__TAURI_INVOKE("core_info", { simulateError })),
	listServices: () => typedError<ServiceStatus[], IpcError>(__TAURI_INVOKE("list_services")),
	startService: (id: string) => typedError<null, IpcError>(__TAURI_INVOKE("start_service", { id })),
	stopService: (id: string) => typedError<null, IpcError>(__TAURI_INVOKE("stop_service", { id })),
	serviceLogTail: (id: string, n: number) => typedError<LogLine[], IpcError>(__TAURI_INVOKE("service_log_tail", { id, n })),
	listSites: () => typedError<SiteDto[], IpcError>(__TAURI_INVOKE("list_sites")),
	/**
	 *  Create a site, optionally scaffolding its docroot folder and a starter
	 *  page (spec: docs/superpowers/specs/2026-07-29-p1-site-scaffold-design.md,
	 *  D2).
	 * 
	 *  Order is load-bearing: ingress guard → join (if `create_folder`) → DB
	 *  insert → THEN scaffold. Scaffolding runs only once `repo.create` has
	 *  actually returned `Ok` — a UNIQUE violation on `name`/`domain` returns
	 *  `Err` from the `?` below and this function stops right there, before the
	 *  `scaffold` line is ever reached, so a rejected create can never leave a
	 *  folder behind.
	 */
	createSite: (input: SiteInput, createFolder: boolean) => typedError<CreateSiteResult, IpcError>(__TAURI_INVOKE("create_site", { input, createFolder })),
	updateSite: (id: string, input: SiteInput) => typedError<SiteDto, IpcError>(__TAURI_INVOKE("update_site", { id, input })),
	deleteSite: (id: string) => typedError<boolean, IpcError>(__TAURI_INVOKE("delete_site", { id })),
	listWebServers: () => typedError<WebServerDto[], IpcError>(__TAURI_INVOKE("list_web_servers")),
	readWebServerConfig: (id: string) => typedError<string, IpcError>(__TAURI_INVOKE("read_web_server_config", { id })),
	validateWebServerConfig: (id: string) => typedError<ValidationReportDto, IpcError>(__TAURI_INVOKE("validate_web_server_config", { id })),
	/**
	 *  Quit after the UI has confirmed it: stop every pending service, then destroy
	 *  the window.
	 * 
	 *  The mechanics and the reasoning live in `crate::quit` — this is only the IPC
	 *  boundary. It takes no arguments on purpose: there is nothing to validate, and
	 *  the command can therefore do exactly one thing no matter who calls it. It is
	 *  NOT the thing that decides to quit; `quit::request_quit` has already asked the
	 *  user, and a caller reaching this directly could only do what the close button
	 *  already does.
	 */
	confirmQuit: () => typedError<null, IpcError>(__TAURI_INVOKE("confirm_quit")),
	/**
	 *  Tell the Rust side that the quit dialog's listener is registered.
	 * 
	 *  Until this lands, a close request is NOT prevented — see `quit::UiReady` for
	 *  why an emit's return value cannot stand in for this. Idempotent and
	 *  unauthenticated by design: the only thing a caller can achieve is enabling a
	 *  confirmation dialog on their own window.
	 */
	quitDialogReady: () => typedError<null, IpcError>(__TAURI_INVOKE("quit_dialog_ready")),
	/**
	 *  Resident memory of everything the supervisor is running.
	 * 
	 *  `try_state` rather than `State<'_, Arc<Supervisor>>`: the supervisor is only
	 *  managed when the setup bootstrap succeeded, and an unmanaged one must give a
	 *  clean error the strip renders as "—" rather than Tauri's raw state panic
	 *  message. Same precedent as the quit path.
	 * 
	 *  The abort-on-`Err` rule (spec §4.1) lives in `collect_readings`, not here —
	 *  see its doc comment for why the read loop was extracted instead of kept
	 *  inline.
	 */
	servicesMemory: () => typedError<ServicesMemoryDto, IpcError>(__TAURI_INVOKE("services_memory")),
	/**
	 *  Total size of the OpenVHost home.
	 * 
	 *  The walk runs on `spawn_blocking`, not inline: it measured 40 ms over 6,470
	 *  files (spec §3.2), which is long enough to matter on a runtime thread, and
	 *  the figure is not urgent.
	 */
	homeDiskUsage: () => typedError<HomeUsageDto, IpcError>(__TAURI_INVOKE("home_disk_usage")),
	/**
	 *  Open a site in the user's default browser.
	 * 
	 *  **The URL is built HERE, in Rust, and the webview never supplies one.** The
	 *  obvious alternative — granting the frontend `opener:allow-open-url` and letting
	 *  it call `openUrl(...)` — would hand the renderer a general "open any URL"
	 *  primitive. This command narrows that to "open the site with this id": the only
	 *  thing a caller can influence is which stored row is used, and the scheme is
	 *  fixed. No capability grant is added to `capabilities/default.json` at all,
	 *  because the ACL gates the JS-to-plugin path and this calls the plugin's Rust
	 *  API instead.
	 * 
	 *  The domain also already passed `Domain`'s charset guard on its way into
	 *  state.db, so it cannot carry a scheme, a path, whitespace or a quote. That
	 *  guard is a charset check and NOT a policy check, though — it does not decide
	 *  which hosts are ours — so this deliberately hardcodes `http://` rather than
	 *  letting a stored value choose the scheme.
	 */
	openSite: (id: string) => typedError<null, IpcError>(__TAURI_INVOKE("open_site", { id })),
	/**
	 *  Open Homebrew's install page in the user's browser.
	 * 
	 *  Zero parameters, and the URL is a Rust literal: the webview cannot choose
	 *  where this goes. Same reasoning as `open_site` above — granting the
	 *  renderer a general "open any URL" primitive is the thing being avoided,
	 *  not the act of opening a URL. No capability grant is added to
	 *  `capabilities/default.json` for the same reason `open_site` needs none:
	 *  this calls the plugin's Rust API, not its JS path, so the ACL (which
	 *  gates the JS-to-plugin path) has nothing to do with it.
	 * 
	 *  This exists because a plain `<a target="_blank">` is inert in this
	 *  webview: Tauri only handles a new-window request when the app registers
	 *  `.on_new_window(...)` on the webview builder, which this app does not, so
	 *  WebKit's `WKUIDelegate` is told not to create a window and the click
	 *  silently does nothing — no tab, no error, no console warning.
	 */
	openHomebrewSite: () => typedError<null, IpcError>(__TAURI_INVOKE("open_homebrew_site")),
	/**
	 *  What Apply would change across the WHOLE generated config — the sites and
	 *  the editable nginx settings both feed `apply_input`, so this is one plan
	 *  over one config set, not a site-only view. (That is the rename: the old
	 *  `plan_site_apply` would have told the reader this covered only sites.)
	 * 
	 *  Read-only and process-free — the pending-changes banner calls this after
	 *  every site mutation and after every settings save.
	 */
	planConfigApply: () => typedError<ApplyPlanDto, IpcError>(__TAURI_INVOKE("plan_config_apply")),
	/**
	 *  Write the generated config — sites AND the editable nginx settings — then
	 *  restart whichever affected services are running.
	 * 
	 *  The restart is the app's job, not core's: `openvhost-core` has no supervisor
	 *  and must stay usable from the CLI.
	 */
	applyConfig: () => typedError<ApplyOutcomeDto, IpcError>(__TAURI_INVOKE("apply_config")),
	/**
	 *  The stored nginx settings, or the documented defaults when the user has
	 *  never saved any.
	 */
	webServerSettings: () => typedError<WebServerSettingsDto, IpcError>(__TAURI_INVOKE("web_server_settings")),
	/**
	 *  Validate and store the nginx settings. Does **not** apply them.
	 * 
	 *  Applying is the user's next, explicit step through `plan_config_apply` /
	 *  `apply_config` — the same pipeline the sites go through, which is why there
	 *  is no settings-only apply command. A second apply path would mean two ways
	 *  for the live config to change, only one of which shows a diff first.
	 * 
	 *  It DOES run `nginx -t` first, over a candidate render of the submitted
	 *  values (`write_settings`). That check renders the user's own values, which
	 *  is why it cannot be `WebServerAdapter::validate` — that call renders with
	 *  *defaults* on purpose, answers "is the shape valid?", and would wave
	 *  through a combination nginx rejects. Measured cost of the spawn is well
	 *  under a frame, against a failure that otherwise surfaces at an unrelated
	 *  later apply.
	 */
	saveWebServerSettings: (input: WebServerSettingsDto) => typedError<null, IpcError>(__TAURI_INVOKE("save_web_server_settings", { input })),
	/**
	 *  Read-only environment summary for the Languages page: whether Homebrew was
	 *  found, where it looked, and one row per PHP version (spec §6.1).
	 * 
	 *  Deliberately spawns NOTHING — it reads the managed `RwLock` and calls
	 *  `find_brew()` (a filesystem check, not a process). It is called on page
	 *  mount and after every install, and the discipline that keeps
	 *  `plan_config_apply` cheap (Task 4's managed `RwLock`, read then cloned and
	 *  dropped before anything else runs) applies here too. `rescan_php_runtimes`
	 *  is the one that actually probes.
	 */
	phpEnvironment: () => typedError<PhpEnvironmentDto, IpcError>(__TAURI_INVOKE("php_environment")),
	/**
	 *  The explicit, user-initiated re-probe behind Languages' "Check again"
	 *  button: the user left to install Homebrew (or a PHP version) in a
	 *  terminal and came back. Unlike `php_environment`, this DOES spawn — once
	 *  per candidate binary, to read its version — so it is never called
	 *  implicitly.
	 * 
	 *  Takes `InstallLock` — the same lock `install_php` holds for its whole
	 *  run — across the entire `rescan_into_state` call. Without it, a rescan is
	 *  a read-modify-write over the managed `RwLock` with nothing serializing it
	 *  against a concurrent install: the rescan can read the OLD set, block on
	 *  probing every candidate binary, and only write its (now stale) result
	 *  back AFTER an in-flight install finished and wrote the new one — silently
	 *  reverting a completed install. `install_php` still returns
	 *  `detected: true` for that install, so the row would say "Installed" while
	 *  the apply pipeline no longer knows the version exists.
	 */
	rescanPhpRuntimes: () => typedError<PhpEnvironmentDto, IpcError>(__TAURI_INVOKE("rescan_php_runtimes")),
	/**
	 *  Install a PHP major via Homebrew, streaming its output live, then rescan
	 *  so the freshly installed version (if it appears) gets a supervisor row.
	 * 
	 *  Every argument that reaches `brew`'s argv is validated or derived from
	 *  managed state before this function does anything observable: `major` is
	 *  parsed and checked against the catalogue allowlist, `brew` is located by
	 *  absolute path (never `PATH`), and `brew_install_spec` itself refuses a
	 *  non-absolute `brew` path.
	 */
	installPhp: (major: string) => typedError<InstallOutcomeDto, IpcError>(__TAURI_INVOKE("install_php", { major })),
	/**
	 *  The PHP major currently installing, if any — for the quit dialog: a build
	 *  in progress is invisible to `pending_service_ids` (it is not a supervised
	 *  service), so without this the confirmation would silently discard it.
	 *  `None` when a MySQL install/init occupies `InstallLock`'s shared slot
	 *  instead — see `InstallKind`'s doc comment.
	 */
	pendingPhpInstall: () => typedError<string | null, IpcError>(__TAURI_INVOKE("pending_php_install")),
	/**
	 *  Read-only environment summary for the Databases page: whether Homebrew
	 *  was found, where it looked, and one row per MySQL major (spec D7).
	 *  Deliberately spawns NOTHING — mirrors `php_environment`'s identical
	 *  contract exactly (reads the managed `RwLock` + `find_brew()`, a
	 *  filesystem check). `rescan_mysql` is the one that actually probes.
	 */
	mysqlEnvironment: () => typedError<MysqlEnvironmentDto, IpcError>(__TAURI_INVOKE("mysql_environment")),
	/**
	 *  The explicit, user-initiated re-probe behind the Databases page's rescan
	 *  affordance — mirrors `rescan_php_runtimes` exactly, including blocking on
	 *  `InstallLock` for the identical reason (a rescan racing a completed
	 *  install must never silently revert it).
	 */
	rescanMysql: () => typedError<MysqlEnvironmentDto, IpcError>(__TAURI_INVOKE("rescan_mysql")),
	/**
	 *  Install a MySQL major via Homebrew, streaming its output live, then
	 *  rescan so a freshly installed version (if it appears) is picked up —
	 *  mirrors `install_php` exactly, sharing `InstallLock` (decision 5) — see
	 *  `InstallKind`'s doc comment for why the quit dialog's PHP-specific copy
	 *  is unaffected by this.
	 */
	installMysql: (major: string) => typedError<MysqlInstallOutcomeDto, IpcError>(__TAURI_INVOKE("install_mysql", { major })),
	/**
	 *  Drives Task 4's staged-init sequence for one MySQL major (spec D2),
	 *  streaming log events live, exactly like `install_php`: `run_task`-style
	 *  child spawning, a held `AbortHandle` (shared `InstallLock`, decision 5),
	 *  a `Drop` guard, streamed events. Renders+validates via Task 3 first;
	 *  registers/refreshes the service ONLY on full success. The pre-flight
	 *  decision (catalogue gate, datadir classification) is
	 *  [`initialize_mysql_gate`] — see its doc comment.
	 */
	initializeMysql: (major: string) => typedError<MysqlInitOutcomeDto, IpcError>(__TAURI_INVOKE("initialize_mysql", { major })),
	/**
	 *  The stored root password for `major` (spec D3's outbound reveal — the
	 *  ONE place this crosses IPC, deliberately, for the masked field's
	 *  Reveal/Copy affordance).
	 */
	mysqlRootPassword: (major: string) => typedError<string, IpcError>(__TAURI_INVOKE("mysql_root_password", { major })),
	/**
	 *  Regenerate MySQL's root password (spec D3: "reset-by-regenerate ships",
	 *  user-chosen deferred): authenticates with the STORED (old) password via
	 *  an ephemeral 0600 defaults-file, runs `ALTER USER` over stdin with a
	 *  freshly generated password, and — only once that succeeds — persists the
	 *  new value. A stale stored password (spec Deferred: "desync between
	 *  state.db and a restored datadir") maps to `AuthFailed`, a distinct,
	 *  renderable outcome, never a generic error.
	 */
	resetMysqlRootPassword: (major: string) => typedError<MysqlResetOutcomeDto, IpcError>(__TAURI_INVOKE("reset_mysql_root_password", { major })),
	/**
	 *  `SELECT VERSION(), @@port` through the running server's socket,
	 *  authenticating with the stored credential via an ephemeral 0600
	 *  defaults-file (spec D7's "it works" moment for the Databases page).
	 */
	verifyMysqlConnection: (major: string) => typedError<MysqlConnectionProofDto, IpcError>(__TAURI_INVOKE("verify_mysql_connection", { major })),
};

/** Events */
export const events = {
	mysqlInitLogEvent: makeEvent<MysqlInitLogEvent>("mysql-init-log-event"),
	mysqlInstallLogEvent: makeEvent<MysqlInstallLogEvent>("mysql-install-log-event"),
	phpInstallLogEvent: makeEvent<PhpInstallLogEvent>("php-install-log-event"),
	quitRequestedEvent: makeEvent<QuitRequestedEvent>("quit-requested-event"),
	serviceLogEvent: makeEvent<ServiceLogEvent>("service-log-event"),
	serviceStateEvent: makeEvent<ServiceStateEvent>("service-state-event"),
};

/* Types */
export type ApplyOutcomeDto = {
	/**  `u32`, not `usize`: specta rejects pointer-sized ints (see lib.rs). */
	applied: number,
	/**  Stopped and successfully started again on the new config. */
	restarted: string[],
	/**
	 *  Services whose config changed but which were not running, so the new
	 *  config takes effect the next time they start.
	 */
	notStarted: string[],
	/**
	 *  Were running and could NOT be brought back — the user has to act.
	 *  Never empty-and-ignored: a service this pipeline stopped and failed to
	 *  restart is the one outcome the UI must not present as success.
	 */
	needsAttention: ServiceProblemDto[],
};

export type ApplyPlanDto = {
	changes: FileChangeDto[],
};

/**
 *  Basic environment facts, assembled by core (not by the Tauri command —
 *  commands stay thin per master plan §5).
 */
export type CoreInfo = {
	/**  Version of the calling application (desktop app or CLI). */
	appVersion: string,
	/**  Operating system, from `std::env::consts::OS` ("macos", "windows", …). */
	os: string,
	/**  CPU architecture, from `std::env::consts::ARCH` ("aarch64", "x86_64", …). */
	arch: string,
	/**  Resolved OpenVHost home directory, for display. */
	openvhostHome: string,
};

/**
 *  The result of `create_site`: the persisted site, plus what scaffolding did
 *  — if it was requested at all.
 * 
 *  `scaffold: None` means "not requested" (the caller passed
 *  `create_folder: false`) — it is NOT a fourth outcome alongside
 *  `Created`/`KeptExisting`/`Failed`, and the UI must not conflate the two.
 */
export type CreateSiteResult = {
	site: SiteDto,
	scaffold: ScaffoldOutcomeDto | null,
};

export type FileChangeDto = {
	path: string,
	/**  "added" | "modified" | "removed" */
	kind: string,
	diff: string,
};

/**
 *  Total bytes under the OpenVHost home. Same bigint check as
 *  [`ServicesMemoryDto`]: a home directory is nowhere near 9 PB.
 */
export type HomeUsageDto = {
	bytes: number,
};

/**
 *  The outcome of an `install_php` call. `detected: false` alongside
 *  `exit_code: Some(0)` is the case that matters most: brew reporting success
 *  while no `php-fpm` appears afterwards is the silent-failure class this
 *  project keeps catching, so the DTO carries it explicitly rather than
 *  leaving the UI to infer it from an empty rescan.
 */
export type InstallOutcomeDto = {
	major: string,
	exitCode: number | null,
	detected: boolean,
};

/**
 *  Serializable command error (spec §7.2). Establishes the pattern:
 *  every command returns `Result<_, IpcError>` and the UI renders failures.
 */
export type IpcError = 
/**  Dev-only simulated failure used to exercise the UI error path. */
{ kind: "simulated" } | 
/**  An error bubbled up from openvhost-core. */
{ kind: "core"; message: string } | 
/**  An error bubbled up from the process supervisor. */
{ kind: "proc"; message: string } | 
/**
 *  A domain value failed validation; `field` names the offending input so
 *  the UI can mark it instead of showing a generic banner.
 */
{ kind: "validation"; field: string; message: string };

export type LogLevel = "info" | "warn" | "error";

export type LogLine = {
	tsMs: number,
	level: LogLevel,
	line: string,
};

/**
 *  `verify_mysql_connection`'s outcome (spec D7: "returns version/port or
 *  failure detail" — the WHOLE contract is outcome-shaped, never an
 *  `IpcError`, so the "Verify connection" button always has something to
 *  render).
 */
export type MysqlConnectionProofDto = { kind: "ok"; version: string; port: number } | { kind: "authFailed"; detail: string } | { kind: "failed"; detail: string };

/**
 *  Mirrors `openvhost_core::mysql::DatadirState` 1:1 as a wire-safe copy
 *  (that type carries no `specta::Type`/`Serialize`, since openvhost-core
 *  does not depend on either) — read from disk every time, never a
 *  state.db boolean (spec D2).
 */
export type MysqlDatadirStateDto = { kind: "notInitialized" } | { kind: "initialized" } | { kind: "foreign"; detail: string };

/**
 *  What the Databases page needs to decide which state to show (spec D6).
 *  `brew_found: false` means the page must guide, not list.
 */
export type MysqlEnvironmentDto = {
	brewFound: boolean,
	brewSearched: string[],
	instances: MysqlInstanceDto[],
};

/**
 *  One line of `initialize_mysql`'s staged-init sequence, streamed live —
 *  same shape as [`MysqlInstallLogEvent`], a separate type so the frontend
 *  can tell an install log from an init log without inspecting content.
 */
export type MysqlInitLogEvent = {
	major: string,
	tsMs: number,
	stream: string,
	line: string,
};

/**
 *  Mirrors `openvhost_core::mysql::MysqlInitOutcome` 1:1 as a wire-safe copy
 *  (spec D7's `initialize_mysql`).
 */
export type MysqlInitOutcomeDto = { kind: "initialized" } | { kind: "alreadyInitialized" } | { kind: "foreign"; detail: string } | { kind: "failed"; step: MysqlInitStepDto; reason: string };

/**
 *  Mirrors `openvhost_core::mysql::MysqlInitStep` 1:1 as a wire-safe copy —
 *  a stable discriminator for the UI, never parsed out of free text (the
 *  `ScaffoldStep` precedent).
 */
export type MysqlInitStepDto = "render" | "validate" | "initialize" | "startTempServer" | "setPassword" | "shutdown" | "finalize";

/**
 *  One line of `brew install mysql@<major>`'s output, forwarded live while an
 *  install runs. Same shape and reasoning as [`PhpInstallLogEvent`].
 */
export type MysqlInstallLogEvent = {
	major: string,
	tsMs: number,
	stream: string,
	line: string,
};

/**  Mirrors `InstallOutcomeDto` for MySQL (spec D7's `install_mysql`). */
export type MysqlInstallOutcomeDto = {
	major: string,
	exitCode: number | null,
	detected: boolean,
};

/**
 *  One row on the Databases page: a catalogue major (installed or not), or
 *  an installed major outside the catalogue (spec D1 — "a user's 9.x
 *  renders as a row without an Install button").
 */
export type MysqlInstanceDto = {
	major: string,
	/**
	 *  Whether THIS BUILD offers to install this major (`MYSQL_CATALOGUE`
	 *  membership) — false means no Install affordance, never a broken one.
	 */
	cataloged: boolean,
	installed: boolean,
	path: string | null,
	/**
	 *  `Some` ONLY once BOTH installed and the datadir is genuinely
	 *  Initialized — exactly when `service_id` also names a real
	 *  supervisor row (never merely "installed", unlike PHP's pool, which
	 *  gets a row the moment it is installed: MySQL's row is gated on the
	 *  datadir too, spec D6).
	 */
	socketPath: string | null,
	serviceId: string | null,
	datadirState: MysqlDatadirStateDto,
};

/**
 *  `reset_mysql_root_password`'s outcome (spec D7 + Deferred: "distinct
 *  auth-failure state"). Auth failure is an EXPECTED, renderable outcome —
 *  the stored password may be stale (a restored/hand-copied datadir) —
 *  never thrown as an `IpcError`; a spawn/other failure still is.
 */
export type MysqlResetOutcomeDto = { kind: "reset" } | { kind: "authFailed"; detail: string };

/**
 *  What the Languages page needs to decide which of the three states to show
 *  (spec §6.1). `brew_found` false means the page must guide, not list.
 */
export type PhpEnvironmentDto = {
	brewFound: boolean,
	brewSearched: string[],
	runtimes: PhpRuntimeDto[],
};

/**
 *  One line of `brew install`'s output, forwarded live while an install runs.
 *  Same shape and reasoning as [`ServiceLogEvent`] — see its declaration —
 *  except `major` names which install this line belongs to, and `stream` is
 *  a plain "stdout"/"stderr" string rather than `LogLevel`: brew's output has
 *  no severity for the supervisor's classifier to assign, only a stream.
 */
export type PhpInstallLogEvent = {
	major: string,
	tsMs: number,
	stream: string,
	line: string,
};

/**
 *  One row on the Languages page: a catalogue version (installed or not), or
 *  an installed version outside the catalogue (spec §6.1's "still listed"
 *  requirement — an install made by hand, or one a later catalogue drops,
 *  must not vanish from the page while it keeps serving sites).
 */
export type PhpRuntimeDto = {
	major: string,
	installed: boolean,
	recommended: boolean,
	/**
	 *  A more precise version string than `major` (e.g. a patch level), when
	 *  one is known. `None` does NOT mean anything is wrong with this row —
	 *  it means we do not know the patch level. The only prober we have,
	 *  `openvhost_conf::probe_php_fpm_version`, returns `major.minor` and
	 *  never a patch level, so today this is `None` for every row. Echoing
	 *  `major` back into this field instead would render "8.3" twice next to
	 *  each other and imply a patch level was fetched when it was not.
	 */
	fullVersion: string | null,
	path: string | null,
	/**  Where this version's pool listens. `None` until installed. */
	socketPath: string | null,
	/**
	 *  The supervisor id for this version's pool, so the UI can drive
	 *  start/stop from the row without inventing the id itself.
	 */
	serviceId: string | null,
};

/**
 *  Emitted to the webview when a quit has been requested and prevented. The UI
 *  answers with the `confirm_quit` command, or does nothing if the user cancels.
 */
export type QuitRequestedEvent = Record<string, never>;

/**
 *  Scaffold outcome crossing IPC. Mirrors `openvhost_core::site::scaffold`'s
 *  `ScaffoldOutcome` — the core crate stays serde/specta-free by design, so
 *  this DTO is the serialization layer, the same seam as `Site` → `SiteDto`.
 *  `kind` is the discriminator the UI switches on exhaustively.
 */
export type ScaffoldOutcomeDto = { kind: "created" } | { kind: "keptExisting"; existing: string } | { kind: "failed"; step: ScaffoldStepDto; reason: string };

/**
 *  Which step of a [`ScaffoldOutcomeDto::Failed`] failed. Mirrors
 *  `openvhost_core::site::scaffold::ScaffoldStep`; never parse English out of
 *  `reason` in the UI — this is the stable discriminator for that.
 */
export type ScaffoldStepDto = "createDir" | "inspect" | "writePlaceholder";

export type ServiceLogEvent = {
	id: string,
	tsMs: number,
	level: LogLevel,
	line: string,
};

export type ServiceProblemDto = {
	id: string,
	/**
	 *  A sentence the UI can show as-is, telling the user what happened and
	 *  what is left for them to do.
	 */
	reason: string,
};

export type ServiceState = { kind: "stopped" } | { kind: "starting" } | { kind: "running" } | { kind: "failed"; exit: number | null; stderrTail: string[] };

export type ServiceStateEvent = {
	id: string,
	state: ServiceState,
	detail: string | null,
};

export type ServiceStatus = {
	id: string,
	displayName: string,
	endpoint: string | null,
	pid: number | null,
	state: ServiceState,
};

/**
 *  Summed resident memory of the supervised services.
 * 
 *  `bytes` and `process_count` are both u64/u32 crossing a
 *  `.dangerously_cast_bigints_to_number()` boundary — see `lib.rs`'s standing
 *  warning, which names "byte totals" as the case requiring a conscious check.
 *  `2^53` bytes is 9 petabytes; a resident set is many orders of magnitude
 *  below it. Checked, not assumed.
 */
export type ServicesMemoryDto = {
	bytes: number,
	/**
	 *  How many pids actually produced a figure — NOT how many services are
	 *  running. See `sum_readings`.
	 */
	processCount: number,
};

/**
 *  A site as it crosses IPC. `Site`'s fields are opaque validated newtypes
 *  (deliberately not serializable), so the wire form is plain strings.
 */
export type SiteDto = {
	id: string,
	name: string,
	domain: string,
	docroot: string,
	webServer: string,
	phpVersion: string,
	enabled: boolean,
	createdAt: number,
	updatedAt: number,
};

/**
 *  Client-supplied site fields. Note there is no `id`/`created_at`/
 *  `updated_at`: those are server-owned and never taken from the client.
 */
export type SiteInput = {
	name: string,
	domain: string,
	docroot: string,
	webServer: string,
	phpVersion: string,
	enabled: boolean,
};

export type ValidationReportDto = {
	ok: boolean,
	stderr: string,
};

/**  One row on the Web Server page. */
export type WebServerDto = {
	id: string,
	displayName: string,
	supported: boolean,
	/**
	 *  Correlates with the shared services store for live status; `None` when
	 *  the brand is not a supervised service.
	 */
	serviceId: string | null,
	binaryPath: string | null,
	version: string | null,
	supportsHotReload: boolean,
	configPath: string | null,
	/**
	 *  Whether a file exists at `config_path` right now — a TRI-STATE, because
	 *  a filesystem stat has three honest outcomes, not two.
	 * 
	 *  `Some(true)`: confirmed present. `Some(false)`: confirmed absent — and
	 *  on a fresh install this is the common case, because `provision_home`
	 *  seeds directories and the welcome page but writes no config (pinned by
	 *  `provisioning_no_longer_writes_any_config`). `None`: the stat could not
	 *  be performed at all (permission denied on a parent directory, a
	 *  dangling symlink from an interrupted atomic write, ...) — this is
	 *  EXISTENCE UNKNOWN, and it must never collapse into `Some(false)`.
	 *  Doing so would tell the user "no config generated yet — apply your
	 *  changes first" when the real cause has nothing to do with Apply and
	 *  re-running it cannot fix it.
	 * 
	 *  EXISTENCE, NOT VALIDITY, in every non-`None` case. nginx is registered
	 *  to spawn with `-c <config_path>`, so a confirmed-missing file means
	 *  Start exits immediately, and the page disables Start on `Some(false)`
	 *  and says why, rather than letting the user find out by pressing it. On
	 *  `None` the page instead leaves Start enabled with no claim about the
	 *  cause — see `startStopFor` — because nginx's own stderr on a genuine
	 *  failure names the real problem, which this DTO cannot. A config that
	 *  exists can still be refused by nginx; that case is the row's stderr
	 *  block, not this flag.
	 */
	configExists: boolean | null,
};

/**
 *  The editable nginx settings as they cross IPC.
 * 
 *  `WebServerSettings`' fields are opaque validated newtypes that carry no
 *  `specta::Type` (and cannot get one without making `openvhost-conf` an IPC
 *  crate), so the wire form is plain primitives. `u32`, never `usize`: specta
 *  rejects pointer-sized ints — see the standing note in `lib.rs`.
 * 
 *  `camelCase` on the wire like every other DTO here, so TypeScript sees
 *  `fastcgiReadTimeout`/`clientMaxBodySize`. Note that the *validation* field
 *  names in [`IpcError::Validation`] are snake_case, because that is what the
 *  existing `fieldErrors` seam is keyed by (see `From<ConfError> for IpcError`).
 */
export type WebServerSettingsDto = {
	workerConnections: number,
	clientMaxBodySize: string,
	keepaliveTimeout: number,
	tcpNodelay: boolean,
	fastcgiConnectTimeout: number,
	fastcgiSendTimeout: number,
	fastcgiReadTimeout: number,
	gzip: boolean,
	gzipCompLevel: number,
	gzipTypes: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

