// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	coreInfo: (simulateError: boolean | null) => typedError<CoreInfo, IpcError>(__TAURI_INVOKE("core_info", { simulateError })),
	listServices: () => typedError<ServiceStatus[], IpcError>(__TAURI_INVOKE("list_services")),
	startService: (id: string) => typedError<null, IpcError>(__TAURI_INVOKE("start_service", { id })),
	stopService: (id: string) => typedError<null, IpcError>(__TAURI_INVOKE("stop_service", { id })),
	serviceLogTail: (id: string, n: number) => typedError<LogLine[], IpcError>(__TAURI_INVOKE("service_log_tail", { id, n })),
	listSites: () => typedError<SiteDto[], IpcError>(__TAURI_INVOKE("list_sites")),
	createSite: (input: SiteInput) => typedError<SiteDto, IpcError>(__TAURI_INVOKE("create_site", { input })),
	updateSite: (id: string, input: SiteInput) => typedError<SiteDto, IpcError>(__TAURI_INVOKE("update_site", { id, input })),
	deleteSite: (id: string) => typedError<boolean, IpcError>(__TAURI_INVOKE("delete_site", { id })),
	listWebServers: () => typedError<WebServerDto[], IpcError>(__TAURI_INVOKE("list_web_servers")),
	readWebServerConfig: (id: string) => typedError<string, IpcError>(__TAURI_INVOKE("read_web_server_config", { id })),
	validateWebServerConfig: (id: string) => typedError<ValidationReportDto, IpcError>(__TAURI_INVOKE("validate_web_server_config", { id })),
	/**
	 *  Quit after the UI has confirmed it: stop every pending service, then destroy
	 *  the window.
	 * 
	 *  The mechanics and the reasoning live in `crate::quit` — this is only the IPC
	 *  boundary. It takes no arguments on purpose: there is nothing to validate, and
	 *  the command can therefore do exactly one thing no matter who calls it. It is
	 *  NOT the thing that decides to quit; `quit::request_quit` has already asked the
	 *  user, and a caller reaching this directly could only do what the close button
	 *  already does.
	 */
	confirmQuit: () => typedError<null, IpcError>(__TAURI_INVOKE("confirm_quit")),
	/**
	 *  Tell the Rust side that the quit dialog's listener is registered.
	 * 
	 *  Until this lands, a close request is NOT prevented — see `quit::UiReady` for
	 *  why an emit's return value cannot stand in for this. Idempotent and
	 *  unauthenticated by design: the only thing a caller can achieve is enabling a
	 *  confirmation dialog on their own window.
	 */
	quitDialogReady: () => typedError<null, IpcError>(__TAURI_INVOKE("quit_dialog_ready")),
	/**
	 *  Resident memory of everything the supervisor is running.
	 * 
	 *  `try_state` rather than `State<'_, Arc<Supervisor>>`: the supervisor is only
	 *  managed when the setup bootstrap succeeded, and an unmanaged one must give a
	 *  clean error the strip renders as "—" rather than Tauri's raw state panic
	 *  message. Same precedent as the quit path.
	 * 
	 *  The abort-on-`Err` rule (spec §4.1) lives in `collect_readings`, not here —
	 *  see its doc comment for why the read loop was extracted instead of kept
	 *  inline.
	 */
	servicesMemory: () => typedError<ServicesMemoryDto, IpcError>(__TAURI_INVOKE("services_memory")),
	/**
	 *  Total size of the OpenVHost home.
	 * 
	 *  The walk runs on `spawn_blocking`, not inline: it measured 40 ms over 6,470
	 *  files (spec §3.2), which is long enough to matter on a runtime thread, and
	 *  the figure is not urgent.
	 */
	homeDiskUsage: () => typedError<HomeUsageDto, IpcError>(__TAURI_INVOKE("home_disk_usage")),
};

/** Events */
export const events = {
	quitRequestedEvent: makeEvent<QuitRequestedEvent>("quit-requested-event"),
	serviceLogEvent: makeEvent<ServiceLogEvent>("service-log-event"),
	serviceStateEvent: makeEvent<ServiceStateEvent>("service-state-event"),
};

/* Types */
/**
 *  Basic environment facts, assembled by core (not by the Tauri command —
 *  commands stay thin per master plan §5).
 */
export type CoreInfo = {
	/**  Version of the calling application (desktop app or CLI). */
	appVersion: string,
	/**  Operating system, from `std::env::consts::OS` ("macos", "windows", …). */
	os: string,
	/**  CPU architecture, from `std::env::consts::ARCH` ("aarch64", "x86_64", …). */
	arch: string,
	/**  Resolved OpenVHost home directory, for display. */
	openvhostHome: string,
};

/**
 *  Total bytes under the OpenVHost home. Same bigint check as
 *  [`ServicesMemoryDto`]: a home directory is nowhere near 9 PB.
 */
export type HomeUsageDto = {
	bytes: number,
};

/**
 *  Serializable command error (spec §7.2). Establishes the pattern:
 *  every command returns `Result<_, IpcError>` and the UI renders failures.
 */
export type IpcError = 
/**  Dev-only simulated failure used to exercise the UI error path. */
{ kind: "simulated" } | 
/**  An error bubbled up from openvhost-core. */
{ kind: "core"; message: string } | 
/**  An error bubbled up from the process supervisor. */
{ kind: "proc"; message: string } | 
/**
 *  A domain value failed validation; `field` names the offending input so
 *  the UI can mark it instead of showing a generic banner.
 */
{ kind: "validation"; field: string; message: string };

export type LogLevel = "info" | "warn" | "error";

export type LogLine = {
	tsMs: number,
	level: LogLevel,
	line: string,
};

/**
 *  Emitted to the webview when a quit has been requested and prevented. The UI
 *  answers with the `confirm_quit` command, or does nothing if the user cancels.
 */
export type QuitRequestedEvent = Record<string, never>;

export type ServiceLogEvent = {
	id: string,
	tsMs: number,
	level: LogLevel,
	line: string,
};

export type ServiceState = { kind: "stopped" } | { kind: "starting" } | { kind: "running" } | { kind: "failed"; exit: number | null; stderrTail: string[] };

export type ServiceStateEvent = {
	id: string,
	state: ServiceState,
	detail: string | null,
};

export type ServiceStatus = {
	id: string,
	displayName: string,
	endpoint: string | null,
	pid: number | null,
	state: ServiceState,
};

/**
 *  Summed resident memory of the supervised services.
 * 
 *  `bytes` and `process_count` are both u64/u32 crossing a
 *  `.dangerously_cast_bigints_to_number()` boundary — see `lib.rs`'s standing
 *  warning, which names "byte totals" as the case requiring a conscious check.
 *  `2^53` bytes is 9 petabytes; a resident set is many orders of magnitude
 *  below it. Checked, not assumed.
 */
export type ServicesMemoryDto = {
	bytes: number,
	/**
	 *  How many pids actually produced a figure — NOT how many services are
	 *  running. See `sum_readings`.
	 */
	processCount: number,
};

/**
 *  A site as it crosses IPC. `Site`'s fields are opaque validated newtypes
 *  (deliberately not serializable), so the wire form is plain strings.
 */
export type SiteDto = {
	id: string,
	name: string,
	domain: string,
	docroot: string,
	webServer: string,
	phpVersion: string,
	enabled: boolean,
	createdAt: number,
	updatedAt: number,
};

/**
 *  Client-supplied site fields. Note there is no `id`/`created_at`/
 *  `updated_at`: those are server-owned and never taken from the client.
 */
export type SiteInput = {
	name: string,
	domain: string,
	docroot: string,
	webServer: string,
	phpVersion: string,
	enabled: boolean,
};

export type ValidationReportDto = {
	ok: boolean,
	stderr: string,
};

/**  One row on the Web Server page. */
export type WebServerDto = {
	id: string,
	displayName: string,
	supported: boolean,
	/**
	 *  Correlates with the shared services store for live status; `None` when
	 *  the brand is not a supervised service.
	 */
	serviceId: string | null,
	binaryPath: string | null,
	version: string | null,
	supportsHotReload: boolean,
	configPath: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

