// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	coreInfo: (simulateError: boolean | null) => typedError<CoreInfo, IpcError>(__TAURI_INVOKE("core_info", { simulateError })),
};

/* Types */
/**
 *  Basic environment facts, assembled by core (not by the Tauri command —
 *  commands stay thin per master plan §5).
 */
export type CoreInfo = {
	/**  Version of the calling application (desktop app or CLI). */
	appVersion: string,
	/**  Operating system, from `std::env::consts::OS` ("macos", "windows", …). */
	os: string,
	/**  CPU architecture, from `std::env::consts::ARCH` ("aarch64", "x86_64", …). */
	arch: string,
	/**  Resolved OpenVHost home directory, for display. */
	openvhostHome: string,
};

/**
 *  Serializable command error (spec §7.2). Establishes the pattern:
 *  every command returns `Result<_, IpcError>` and the UI renders failures.
 */
export type IpcError = 
/**  Dev-only simulated failure used to exercise the UI error path. */
{ kind: "simulated" } | 
/**  An error bubbled up from openvhost-core. */
{ kind: "core"; message: string };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

