// SPDX-License-Identifier: GPL-3.0-or-later
//! macOS home provisioning.
//!
//! Historically this module also wrote a hand-rolled nginx + php-fpm config
//! set (P0-4 demo stack). That is retired: `site::apply` (portable, not
//! macOS-only) now owns every generated file under
//! `<home>/config/generated/`. What remains here is OS-independent-in-spirit
//! but macOS-specific in location: create the directories the generated
//! config set expects, seed the welcome page, and resolve the Homebrew
//! binaries the supervised services spawn.

use std::path::{Path, PathBuf};

use crate::error::CoreError;

/// Homebrew binaries for the stack. Resolve at registration time: the
/// `opt/` symlinks silently retarget on major version bumps.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BrewStack {
    pub nginx: PathBuf,
    pub php_fpm: PathBuf,
}

/// Probe the standard Homebrew prefixes (Apple Silicon first, then Intel).
pub fn find_brew_binaries() -> Option<BrewStack> {
    let prefixes: Vec<&Path> = crate::php::BREW_PREFIXES.iter().map(Path::new).collect();
    find_brew_binaries_in(&prefixes)
}

/// Pure prober: first prefix holding BOTH binaries wins.
pub fn find_brew_binaries_in(prefixes: &[&Path]) -> Option<BrewStack> {
    prefixes.iter().find_map(|p| {
        let nginx = p.join("opt/nginx/bin/nginx");
        let php_fpm = p.join("opt/php/sbin/php-fpm");
        if nginx.is_file() && php_fpm.is_file() {
            Some(BrewStack { nginx, php_fpm })
        } else {
            None
        }
    })
}

/// The catch-all's landing page — served for any `Host` that matches no site,
/// so it is reachable by every local process and, under DNS rebinding, by a
/// web page. `phpinfo()` was rejected for that reason (security audit A1,
/// 2026-07-27): it discloses absolute paths, the extension inventory and every
/// `php.ini` value to anyone who can reach `127.0.0.1:8080`.
///
/// Echoing `PHP_VERSION` keeps the one property the page is actually for —
/// proving the nginx→php-fpm handshake works end to end — at a fraction of the
/// disclosure. It stays a `.php` file precisely so a static hit cannot pass for
/// a working PHP stack.
///
/// Rewritten on every launch, hence the banner: this file is ours, not the
/// user's, and an edit here would silently vanish.
const INDEX_PHP: &str = r#"<!-- GENERATED by OpenVHost — DO NOT EDIT. Rewritten on every launch. -->
<!doctype html>
<meta charset="utf-8">
<title>OpenVHost</title>
<h1>OpenVHost is running</h1>
<p>PHP <?php echo PHP_VERSION; ?> answered this request, so nginx and php-fpm are talking.</p>
<p>This is the catch-all: the host you requested matches no site yet. Add one in OpenVHost, press Apply, then open it on port 8080.</p>
"#;

/// Create the directories the generated config set expects and seed the
/// welcome page. Writes NO configuration: `site::apply` owns every generated
/// file now.
///
/// Also seeds `logs` itself — the parent of the GLOBAL nginx access+error
/// logs (the aggregate of EVERY site's requests; security audit L2) — plus
/// `logs/sites` and `logs/services`, the two parent directories under which
/// `site::apply::commit` creates a per-site or per-major directory during an
/// Apply (P1 live-log-viewer design, spec D2). All three are created at mode
/// `0700` (spec D5) via the same [`crate::logs::ensure_log_dir`] `commit()`
/// itself uses, rather than `logs` alone inheriting whatever the ambient
/// umask gives a plain `create_dir_all` (typically `0755`) — so every
/// directory directly under `logs/` enforces "0700 explicitly, not merely
/// inherited" from the one shared function, not two independent copies plus
/// an unguarded exception for the parent itself.
pub fn provision_home(home: &Path) -> Result<(), CoreError> {
    std::fs::create_dir_all(home).map_err(|source| CoreError::ProvisionIo {
        op: "create_dir_all",
        path: home.to_path_buf(),
        source,
    })?;
    lock_down_home(home)?;
    for dir in ["www", "run", "run/nginx"] {
        let d = home.join(dir);
        std::fs::create_dir_all(&d).map_err(|source| CoreError::ProvisionIo {
            op: "create_dir_all",
            path: d.clone(),
            source,
        })?;
    }
    for dir in ["logs", "logs/sites", "logs/services"] {
        let d = home.join(dir);
        crate::logs::ensure_log_dir(&d).map_err(|source| CoreError::ProvisionIo {
            op: "create_log_dir",
            path: d.clone(),
            source,
        })?;
    }
    atomic_write(&home.join("www/index.php"), INDEX_PHP)
}

/// Lock `home` itself down to 0700 (security audit H1, the merge blocker):
/// spec D3's at-rest argument for the MySQL root credential stored in
/// `state.db` (`crate::db::Db::open`, which separately guarantees the file
/// itself is 0600) assumes `<home>` is 0700 — otherwise any other local
/// account can walk in and read it (macOS puts every account in the `staff`
/// group, and `/Users/<name>` is group-traversable by default). Applied
/// UNCONDITIONALLY on every call, not only when this function is the one
/// that creates `home`: `set_permissions` sets the exact bits regardless of
/// the ambient umask or of whatever a previous run (or an install that
/// predates this fix) most recently left it at, so an existing install is
/// tightened the very next time it launches, not only a fresh one.
#[cfg(unix)]
fn lock_down_home(home: &Path) -> Result<(), CoreError> {
    use std::os::unix::fs::PermissionsExt;
    std::fs::set_permissions(home, std::fs::Permissions::from_mode(0o700)).map_err(|source| {
        CoreError::ProvisionIo {
            op: "set_permissions",
            path: home.to_path_buf(),
            source,
        }
    })
}
/// Windows single-instance/permission model is deferred (macOS-first, plan
/// §7) — a no-op here rather than a fabricated ACL call keeps this honest
/// about what is and is not implemented, mirroring
/// `openvhost_proc::orphan::lock::InstanceLock::acquire`'s identical
/// `#[cfg(not(unix))]` posture.
#[cfg(not(unix))]
fn lock_down_home(_home: &Path) -> Result<(), CoreError> {
    Ok(())
}

/// Atomic write: temp file in the SAME directory as the target (same-volume
/// rename — never TMPDIR), then rename over the target.
fn atomic_write(path: &Path, contents: &str) -> Result<(), CoreError> {
    let file_name = path
        .file_name()
        .ok_or_else(|| CoreError::ProvisionIo {
            op: "file_name",
            path: path.to_path_buf(),
            source: std::io::Error::new(std::io::ErrorKind::InvalidInput, "no file name"),
        })?
        .to_string_lossy()
        .into_owned();
    let tmp = path.with_file_name(format!(".{file_name}.tmp"));
    std::fs::write(&tmp, contents).map_err(|source| CoreError::ProvisionIo {
        op: "write",
        path: tmp.clone(),
        source,
    })?;
    std::fs::rename(&tmp, path).map_err(|source| CoreError::ProvisionIo {
        op: "rename",
        path: path.to_path_buf(),
        source,
    })
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    use super::*;

    /// Short-path tempdir: /tmp keeps generated paths far under Darwin's
    /// 104-byte `sun_path` limit (TMPDIR is /var/folders/... and brittle-long).
    fn short_home() -> tempfile::TempDir {
        tempfile::Builder::new()
            .prefix("ovh")
            .tempdir_in("/tmp")
            .unwrap()
    }

    // The `provision_home` directory/seed/idempotency contract is proved by
    // the integration tests in `tests/macos_stack.rs`, not duplicated here.

    #[test]
    fn brew_prober_requires_both_binaries_in_one_prefix() {
        let fake = short_home();
        let prefix = fake.path();
        std::fs::create_dir_all(prefix.join("opt/nginx/bin")).unwrap();
        std::fs::create_dir_all(prefix.join("opt/php/sbin")).unwrap();
        std::fs::write(prefix.join("opt/nginx/bin/nginx"), "").unwrap();
        // Only nginx present -> None.
        assert!(find_brew_binaries_in(&[prefix]).is_none());
        std::fs::write(prefix.join("opt/php/sbin/php-fpm"), "").unwrap();
        let stack = find_brew_binaries_in(&[prefix]).unwrap();
        assert_eq!(stack.nginx, prefix.join("opt/nginx/bin/nginx"));
        assert_eq!(stack.php_fpm, prefix.join("opt/php/sbin/php-fpm"));
    }
}
