// SPDX-License-Identifier: GPL-3.0-or-later
//! The tray / menu-bar quick-controls slice (P1 tray design
//! `docs/superpowers/specs/2026-07-31-p1-tray-design.md`).
//!
//! - `model` (Phase A): the pure menu model — labels, enablement, aggregate
//!   icon state. No tray, no menu, no AppKit (spec D9).
//! - `apply` (this phase): diff two [`model::TrayModel`]s and call the
//!   minimal [`apply::TraySink`] methods needed, against either a recording
//!   test fake or [`TrayHandle`] below.
//! - This file (Phase B): the real `muda`/`tray-icon` construction, the
//!   supervisor-event subscriber that keeps it live, and
//!   [`handle_tray_menu_id`], the click router.
//!
//! **Scope note (spec D10 — Windows is out for this slice).** Nothing in
//! this file is `#[cfg(target_os = "macos")]`-gated at its DEFINITION: the
//! `tray-icon`/`muda` APIs used here are already cross-platform (the
//! `tray-icon` Cargo feature turns on `tauri::tray` for every desktop
//! target, not just macOS), and gating the code itself would make it
//! unusable as a seam for a future Windows-enablement slice. What IS gated
//! is the one CALL SITE in `lib.rs` that invokes [`build`] — matching
//! `quit::app_menu`'s existing precedent — because the four shipped icons
//! are macOS `setTemplate` assets (spec D5) and D10 explicitly defers
//! Windows's own (coloured, non-template) icon set to a later slice. A
//! Windows-enablement slice needs to add Windows icons and un-gate that one
//! call site; it does not need to touch this module's logic.

pub mod apply;
pub mod model;

use std::sync::{Arc, Mutex};

use apply::{TraySink, apply};
use model::{Action, BulkState, IconState, TrayModel, toggle_action, tray_model};
use openvhost_proc::{Supervisor, SupervisorEvent};
use tauri::image::Image;
use tauri::menu::{IsMenuItem, Menu, MenuItem, PredefinedMenuItem};
use tauri::tray::{TrayIcon, TrayIconBuilder};
use tauri::{AppHandle, Manager, Runtime};

/// "Open OpenVHost" row's menu-item id (spec D2's menu layout; also the
/// action `RunEvent::Reopen`/a Dock click perform — see `lib.rs`'s
/// `reopen_window`, which this dispatches the same three calls as).
pub const OPEN_MENU_ITEM_ID: &str = "openvhost:tray:open";
/// The disabled aggregate-summary row's id. Never dispatched (it is
/// rendered `enabled: false`) — reserved so `MenuItem::with_id` has
/// something namespaced to assign rather than an auto-generated id.
pub const SUMMARY_MENU_ITEM_ID: &str = "openvhost:tray:summary";
/// "Start all" row's id. Recognized by [`build`] (so the row exists and its
/// enabled state tracks [`TrayModel::start_all_enabled`]) but NOT yet
/// dispatched by [`handle_tray_menu_id`] — bulk start (`BulkLock`, spec D7)
/// is a later task in this same slice's plan; see that function's doc
/// comment.
pub const START_ALL_MENU_ITEM_ID: &str = "openvhost:tray:start-all";
/// "Stop all" row's id. Same status as [`START_ALL_MENU_ITEM_ID`].
pub const STOP_ALL_MENU_ITEM_ID: &str = "openvhost:tray:stop-all";

/// Index the per-service rows are inserted/removed at: Open (0), summary
/// (1), Start all (2), Stop all (3), a leading separator (4) — rows begin
/// at 5, followed by a trailing separator and Quit.
const ROWS_START_INDEX: usize = 5;

/// The tray icon's glyph for `state`, embedded at compile time (spec D5).
///
/// 36x36 PNGs (`tray-icon` scales to 18pt, so 36px is exactly 2x for
/// Retina), template images (mask-only — see
/// `icons/tray/generate_tray_icons.py`'s module docs for the full
/// geometry/legibility reasoning), generated by and committed alongside
/// that script rather than hand-drawn, so they are reproducible from
/// source. Deliberately NOT added to `tauri.conf.json`'s `bundle.icon`
/// (spec D2/Task 4 brief): those are the app/dock icon set, a completely
/// different asset with a completely different design (brand guidelines
/// Sec 7.2 vs 7.3).
fn icon_for_state(state: IconState) -> Image<'static> {
    match state {
        IconState::Stopped => tauri::include_image!("icons/tray/stopped.png"),
        IconState::Running => tauri::include_image!("icons/tray/running.png"),
        IconState::Starting => tauri::include_image!("icons/tray/starting.png"),
        IconState::Failed => tauri::include_image!("icons/tray/failed.png"),
    }
}

/// Route a menu-item id to its action (spec D2/D6/D9).
///
/// Despite living in `tray`, this is the ONE router for every menu event
/// the whole app receives, not only tray-originated ones: tauri's
/// `on_menu_event` fires "for any menu event, whether it is coming from
/// this window, another window or from the tray icon menu" (verified
/// against the resolved tauri 2.11.5, `tray/mod.rs`'s own doc comment on
/// `TrayIconBuilder::on_menu_event` — there is exactly one global listener
/// list, so a second, tray-specific registration would double-dispatch
/// every id, not add coverage). `lib.rs` wires its single
/// `Builder::on_menu_event` closure straight to this function, which is
/// why the app's macOS menu-bar Quit and the tray's own rows both arrive
/// here.
///
/// Takes a raw `&str` id, not a `tauri::menu::MenuEvent` (spec D9): a
/// `MenuEvent` cannot be constructed in a test (its only field is a
/// private `MenuId`), so a router shaped around one would be unreachable
/// under `mock_builder`. The caller passes `event.id().as_ref()`.
///
/// Re-reads `Supervisor::snapshot()` and derives the action from the
/// CURRENT state via [`toggle_action`] — it never trusts the label the row
/// was rendered with (spec D2's "staleness is closed by construction"):
/// the menu can be showing a state that is already stale by the time a
/// click lands, since recomputation only happens on the next event.
///
/// Dispatch to the supervisor is wrapped in [`tauri::async_runtime::spawn`]
/// rather than called inline: `on_menu_event` fires on the native main
/// thread, which is NOT a tokio worker thread, and `Supervisor::start`
/// documents that it "must be called from within a tokio runtime context"
/// (it does a bare `tokio::spawn` internally). `tauri::async_runtime::spawn`
/// explicitly `.enter()`s tauri's own runtime before spawning (verified
/// against the resolved tauri 2.11.5, `async_runtime.rs:110`), which is
/// what makes this safe from a bare native callback; calling `sup.start`
/// directly here would panic off the main thread with "there is no
/// reactor running" the first time a tray click landed outside of any
/// already-async context.
///
/// An id that matches no known service — this includes the reserved
/// [`START_ALL_MENU_ITEM_ID`]/[`STOP_ALL_MENU_ITEM_ID`]/
/// [`SUMMARY_MENU_ITEM_ID`] strings, whose bulk/no-op dispatch is a later
/// task in this slice's plan — is a deliberate no-op: an unrecognized id
/// must never panic or guess at an action.
pub fn handle_tray_menu_id<R: Runtime>(app: &AppHandle<R>, id: &str) {
    if id == crate::quit::QUIT_MENU_ITEM_ID {
        if !crate::quit::request_quit(app) {
            let handle = app.clone();
            tauri::async_runtime::spawn(async move {
                if let Err(e) = crate::quit::perform_quit(&handle).await {
                    eprintln!("openvhost: quit failed: {e}");
                }
            });
        }
        return;
    }

    if id == OPEN_MENU_ITEM_ID {
        if let Some(window) = app.get_webview_window("main") {
            let _ = window.show();
            let _ = window.unminimize();
            let _ = window.set_focus();
        }
        return;
    }

    let Some(sup) = app.try_state::<Arc<Supervisor>>().map(|s| Arc::clone(&s)) else {
        return;
    };
    let Some(status) = sup.snapshot().into_iter().find(|s| s.id == id) else {
        return;
    };
    match toggle_action(&status.id, &status.state) {
        Action::Start(sid) | Action::Retry(sid) => {
            tauri::async_runtime::spawn(async move {
                let _ = sup.start(&sid);
            });
        }
        Action::Stop(sid) => {
            tauri::async_runtime::spawn(async move {
                let _ = sup.stop(&sid);
            });
        }
        Action::None => {}
    }
}

/// The real [`TraySink`]: holds every native handle a diff might need to
/// mutate, plus the last-applied model to diff the next snapshot against.
struct TrayHandle<R: Runtime> {
    tray_icon: TrayIcon<R>,
    summary_item: MenuItem<R>,
    start_all_item: MenuItem<R>,
    stop_all_item: MenuItem<R>,
    menu: Menu<R>,
    /// Current per-service rows, in display order, alongside their
    /// `MenuItem` handles — the thing [`TraySink::rebuild`] tears down and
    /// replaces on a membership change.
    rows: Mutex<Vec<(String, MenuItem<R>)>>,
    /// The model [`apply`] last diffed against, updated after every apply
    /// call. Read/written only from inside the single
    /// `run_on_main_thread` closure in [`build`]'s subscriber task, so a
    /// plain `Mutex` (not swapped concurrently) is enough.
    last_model: Mutex<TrayModel>,
}

impl<R: Runtime> TraySink for TrayHandle<R> {
    fn set_summary(&self, text: &str) {
        if let Err(e) = self.summary_item.set_text(text) {
            eprintln!("openvhost: failed to update the tray summary: {e}");
        }
    }

    fn set_icon(&self, state: IconState) {
        if let Err(e) = self
            .tray_icon
            .set_icon_with_as_template(Some(icon_for_state(state)), true)
        {
            eprintln!("openvhost: failed to update the tray icon: {e}");
        }
    }

    fn set_start_all_enabled(&self, enabled: bool) {
        if let Err(e) = self.start_all_item.set_enabled(enabled) {
            eprintln!("openvhost: failed to update Start all: {e}");
        }
    }

    fn set_stop_all_enabled(&self, enabled: bool) {
        if let Err(e) = self.stop_all_item.set_enabled(enabled) {
            eprintln!("openvhost: failed to update Stop all: {e}");
        }
    }

    fn set_row_label(&self, id: &str, label: &str) {
        let rows = self.rows.lock().unwrap_or_else(|e| e.into_inner());
        if let Some((_, item)) = rows.iter().find(|(row_id, _)| row_id == id)
            && let Err(e) = item.set_text(label)
        {
            eprintln!("openvhost: failed to update tray row {id}: {e}");
        }
    }

    fn set_row_enabled(&self, id: &str, enabled: bool) {
        let rows = self.rows.lock().unwrap_or_else(|e| e.into_inner());
        if let Some((_, item)) = rows.iter().find(|(row_id, _)| row_id == id)
            && let Err(e) = item.set_enabled(enabled)
        {
            eprintln!("openvhost: failed to enable/disable tray row {id}: {e}");
        }
    }

    /// Tear down every current per-service `MenuItem` and rebuild the row
    /// section from `model.rows`, THEN resync summary/icon/bulk enablement
    /// too. The trailing resync is deliberate, not an afterthought:
    /// [`apply`] calls `rebuild` INSTEAD of the granular per-field diffs
    /// when membership changes (see its doc comment), so if this method
    /// only touched rows, a membership change that ALSO flips the
    /// aggregate icon (almost always true — a newly `Registered` service
    /// is `Stopped`, which can only raise or hold the aggregate, never by
    /// itself lower it before the caller's next diff) would leave the old
    /// icon/summary stale until some LATER event happened to change them
    /// again.
    fn rebuild(&self, model: &TrayModel) {
        let app = self.menu.app_handle().clone();
        let mut rows = self.rows.lock().unwrap_or_else(|e| e.into_inner());
        for (_, item) in rows.drain(..) {
            if let Err(e) = self.menu.remove(&item) {
                eprintln!("openvhost: failed to remove a stale tray row: {e}");
            }
        }

        let mut new_items: Vec<MenuItem<R>> = Vec::with_capacity(model.rows.len());
        for row in &model.rows {
            match MenuItem::with_id(&app, row.id.clone(), &row.label, row.enabled, None::<&str>) {
                Ok(item) => new_items.push(item),
                Err(e) => eprintln!("openvhost: failed to build tray row {}: {e}", row.id),
            }
        }
        let refs: Vec<&dyn IsMenuItem<R>> =
            new_items.iter().map(|i| i as &dyn IsMenuItem<R>).collect();
        if let Err(e) = self.menu.insert_items(&refs, ROWS_START_INDEX) {
            eprintln!("openvhost: failed to insert refreshed tray rows: {e}");
        }

        *rows = model
            .rows
            .iter()
            .map(|r| r.id.clone())
            .zip(new_items)
            .collect();
        drop(rows);

        self.set_summary(&model.summary);
        self.set_icon(model.icon);
        self.set_start_all_enabled(model.start_all_enabled);
        self.set_stop_all_enabled(model.stop_all_enabled);
    }
}

/// Build the tray: the initial menu from `supervisor.snapshot()`, and a
/// background task that keeps it live (spec D2).
///
/// On every `StateChanged`/`Registered` event (and, conservatively, on a
/// `Lagged` notification — see the inline comment at the subscriber loop),
/// recomputes a fresh [`TrayModel`] and applies it. Never applies event
/// deltas: the model is always rebuilt from a fresh `snapshot()`, which is
/// what makes this immune to the broadcast channel's `Lagged` arm (spec
/// D2) — a dropped batch of events just means the next recompute catches
/// up to current reality, rather than needing to replay what was missed.
///
/// **Critical mechanic:** `MenuItem::set_text`/`set_enabled` (and
/// `Menu::insert`/`remove`) are each their own blocking main-thread
/// round-trip (verified against the resolved tauri 2.11.5,
/// `menu/mod.rs`'s `run_item_main_thread!` macro: a channel send, a
/// `run_on_main_thread` dispatch, and a blocking `recv` on the calling
/// thread). Called one-by-one from this event task, N changed fields would
/// mean N such round-trips, each one blocking a tokio worker for as long
/// as the main thread takes to service it — which can be a while if the
/// user is holding the menu open (a native menu runs its own nested run
/// loop). Wrapping the ENTIRE diff-and-apply in one
/// `AppHandle::run_on_main_thread` closure collapses that to a single
/// dispatch: once code is executing INSIDE that closure, it is genuinely
/// on the main thread, so every nested `MenuItem`/`Menu` call's own
/// internal `run_on_main_thread` detects "already on this thread" and
/// runs inline instead of posting-and-waiting (verified against the
/// resolved tauri-runtime-wry 2.11.4, `send_user_message`'s
/// `current_thread().id() == context.main_thread_id` check) — so batching
/// is not just fewer trips in theory, it is genuinely zero EXTRA
/// cross-thread trips beyond the one this function issues itself.
///
/// Rebuilds the row section only when the SET of service ids changes
/// (spec D2) — see [`apply`]'s own doc comment for the exact rule; this
/// function only has to call it.
pub fn build<R: Runtime>(app: &AppHandle<R>, supervisor: Arc<Supervisor>) -> tauri::Result<()> {
    let initial = tray_model(&supervisor.snapshot(), BulkState::Idle);

    let open_item =
        MenuItem::with_id(app, OPEN_MENU_ITEM_ID, "Open OpenVHost", true, None::<&str>)?;
    let summary_item = MenuItem::with_id(
        app,
        SUMMARY_MENU_ITEM_ID,
        &initial.summary,
        false,
        None::<&str>,
    )?;
    let start_all_item = MenuItem::with_id(
        app,
        START_ALL_MENU_ITEM_ID,
        "Start all",
        initial.start_all_enabled,
        None::<&str>,
    )?;
    let stop_all_item = MenuItem::with_id(
        app,
        STOP_ALL_MENU_ITEM_ID,
        "Stop all",
        initial.stop_all_enabled,
        None::<&str>,
    )?;
    let leading_separator = PredefinedMenuItem::separator(app)?;
    let trailing_separator = PredefinedMenuItem::separator(app)?;
    let quit_item = MenuItem::with_id(
        app,
        crate::quit::QUIT_MENU_ITEM_ID,
        "Quit OpenVHost",
        true,
        None::<&str>,
    )?;

    let mut row_items: Vec<MenuItem<R>> = Vec::with_capacity(initial.rows.len());
    for row in &initial.rows {
        row_items.push(MenuItem::with_id(
            app,
            row.id.clone(),
            &row.label,
            row.enabled,
            None::<&str>,
        )?);
    }

    let menu = Menu::new(app)?;
    menu.append(&open_item)?;
    menu.append(&summary_item)?;
    menu.append(&start_all_item)?;
    menu.append(&stop_all_item)?;
    menu.append(&leading_separator)?;
    for item in &row_items {
        menu.append(item)?;
    }
    menu.append(&trailing_separator)?;
    menu.append(&quit_item)?;

    let tray_icon = TrayIconBuilder::new()
        .icon(icon_for_state(initial.icon))
        .icon_as_template(true)
        .menu(&menu)
        .show_menu_on_left_click(true)
        .tooltip("OpenVHost")
        .build(app)?;

    let rows: Vec<(String, MenuItem<R>)> = initial
        .rows
        .iter()
        .map(|r| r.id.clone())
        .zip(row_items)
        .collect();

    let handle = Arc::new(TrayHandle {
        tray_icon,
        summary_item,
        start_all_item,
        stop_all_item,
        menu,
        rows: Mutex::new(rows),
        last_model: Mutex::new(initial),
    });
    // A second strong reference, tying the tray's lifetime to the App's own
    // managed-state lifetime in addition to the subscriber task below —
    // belt-and-suspenders: the task's infinite loop already keeps `handle`
    // alive for the app's lifetime today, but pinning it to managed state
    // too means a future refactor of that loop cannot silently shorten the
    // tray's lifetime without also touching this line.
    app.manage(Arc::clone(&handle));

    let mut rx = supervisor.subscribe();
    let app_for_task = app.clone();
    tauri::async_runtime::spawn(async move {
        loop {
            let refresh = match rx.recv().await {
                Ok(SupervisorEvent::StateChanged { .. } | SupervisorEvent::Registered { .. }) => {
                    true
                }
                // A log line never changes a ServiceStatus's id/display_name/
                // endpoint/pid/state — the only fields `tray_model` reads —
                // so recomputing here would be a guaranteed-no-op diff at
                // whatever rate the busiest service logs. This is NOT
                // "applying an event delta" (spec D2's actual rule): the
                // recompute below always re-reads a fresh `snapshot()`
                // regardless of which event triggered it; skipping Log is
                // only a decision about WHEN to bother, never about what
                // to apply.
                Ok(SupervisorEvent::Log { .. }) => false,
                // Unlike a plain skip, a lagged receiver may have missed a
                // StateChanged/Registered entirely — recompute defensively
                // rather than risk staying stale until the next real event.
                Err(tokio::sync::broadcast::error::RecvError::Lagged(_)) => true,
                Err(tokio::sync::broadcast::error::RecvError::Closed) => break,
            };
            if !refresh {
                continue;
            }
            let snapshot = supervisor.snapshot();
            let handle = Arc::clone(&handle);
            // See this function's own doc comment ("critical mechanic") for
            // why the WHOLE diff-and-apply below lives inside this one
            // `run_on_main_thread` closure rather than being called from
            // this async task directly.
            let _ = app_for_task.run_on_main_thread(move || {
                // `BulkState::Idle` unconditionally: the real `BulkLock` this
                // should read from is a later task in this slice's plan
                // (spec D7) — until it lands, nothing can hold the lock, so
                // `Idle` is the only truthful answer, not a stand-in.
                let new_model = tray_model(&snapshot, BulkState::Idle);
                let mut last = handle.last_model.lock().unwrap_or_else(|e| e.into_inner());
                apply(&last, &new_model, handle.as_ref());
                *last = new_model;
            });
        }
    });

    Ok(())
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;
    use openvhost_proc::{
        DEFAULT_GRACE, ReadinessProbe, ServiceSpec, ServiceState, SpawnSpec, default_driver,
    };
    use std::ffi::OsString;
    use std::path::PathBuf;
    use std::time::{Duration, Instant};

    fn app_with_supervisor() -> (tauri::App<tauri::test::MockRuntime>, Arc<Supervisor>) {
        let app = tauri::test::mock_builder()
            .build(tauri::test::mock_context(tauri::test::noop_assets()))
            .unwrap();
        let sup = Arc::new(Supervisor::new(default_driver()));
        app.manage(Arc::clone(&sup));
        (app, sup)
    }

    /// A real, harmless, long-lived child (mirrors `quit.rs`'s own
    /// `#[cfg(unix)]` precedent for exercising a REAL `Supervisor` rather
    /// than a spec pointing at a nonexistent binary): sleeps far longer
    /// than this test's deadline, so it is still alive for the STOP half
    /// of the test to act on.
    #[cfg(unix)]
    fn sleepy_spec(id: &str) -> ServiceSpec {
        ServiceSpec {
            id: id.to_string(),
            display_name: id.to_string(),
            endpoint: None,
            spawn: SpawnSpec {
                program: PathBuf::from("/bin/sh"),
                args: vec![OsString::from("-c"), OsString::from("exec sleep 30")],
                cwd: None,
                env: vec![],
            },
            readiness: ReadinessProbe::default(),
            grace: DEFAULT_GRACE,
        }
    }

    /// Polls `condition` until it is true or `deadline` elapses, sleeping
    /// briefly between attempts. Panics with `msg` on timeout — mirrors the
    /// polling style already established in `quit.rs`'s own tests, adapted
    /// to a plain synchronous `#[test]` (no `#[tokio::test]` needed here:
    /// `handle_tray_menu_id`'s dispatch runs on tauri's OWN internal
    /// runtime via `tauri::async_runtime::spawn`, not on whatever runtime —
    /// if any — the calling test happens to run under).
    fn wait_until(mut condition: impl FnMut() -> bool, deadline: Duration, msg: &str) {
        let start = Instant::now();
        while !condition() {
            if start.elapsed() >= deadline {
                panic!("{msg}");
            }
            std::thread::sleep(Duration::from_millis(20));
        }
    }

    // -----------------------------------------------------------------
    // handle_tray_menu_id: unknown id is a no-op.
    // -----------------------------------------------------------------

    /// VACUITY (neuter-and-watch-it-fail): temporarily replaced the
    /// exact-id lookup (`.find(|s| s.id == id)`) with `.next()` — i.e. "the
    /// router matches WHATEVER service happens to be first, not
    /// necessarily the one that was clicked". This test failed: the
    /// reserved `START_ALL_MENU_ITEM_ID`/`STOP_ALL_MENU_ITEM_ID`/
    /// `SUMMARY_MENU_ITEM_ID` ids (and the bogus `"does-not-exist"`) all
    /// incorrectly matched the one registered service (`nginx`, the only
    /// row) and started it — `sup.snapshot()` after no longer equaled
    /// `before`. Restoring the exact-id `find` made it pass again.
    #[test]
    fn unknown_id_changes_nothing_and_does_not_panic() {
        let (app, sup) = app_with_supervisor();
        sup.register(sleepy_spec("nginx"));
        let before = sup.snapshot();

        handle_tray_menu_id(app.handle(), "does-not-exist");
        handle_tray_menu_id(app.handle(), START_ALL_MENU_ITEM_ID);
        handle_tray_menu_id(app.handle(), STOP_ALL_MENU_ITEM_ID);
        handle_tray_menu_id(app.handle(), SUMMARY_MENU_ITEM_ID);

        // Give a wrongly-dispatching implementation a real chance to have
        // acted before asserting nothing changed.
        std::thread::sleep(Duration::from_millis(100));
        assert_eq!(sup.snapshot(), before);
    }

    /// No managed `Supervisor` at all must also be a no-op, not a panic —
    /// mirrors `quit.rs`'s own "nothing managed yet" posture for every
    /// other `try_state` read in this app.
    #[test]
    fn unknown_id_with_no_managed_supervisor_does_not_panic() {
        let app = tauri::test::mock_builder()
            .build(tauri::test::mock_context(tauri::test::noop_assets()))
            .unwrap();
        handle_tray_menu_id(app.handle(), "nginx");
    }

    // -----------------------------------------------------------------
    // handle_tray_menu_id: per-service start/stop dispatch, under a real
    // managed Supervisor with a real spawned child.
    // -----------------------------------------------------------------

    /// VACUITY (neuter-and-watch-it-fail): temporarily replaced the
    /// `toggle_action` match with an unconditional `sup.start(&sid)` (i.e.
    /// dispatch Start regardless of the service's current state). The
    /// START half of this test still passed against that neuter, but the
    /// STOP half failed: the service never left `Running` because a
    /// second `start` is a documented no-op on an already-`Starting`/
    /// `Running` service (`Supervisor::start`'s own doc comment), so
    /// `wait_until` timed out waiting for `Stopped`. This is exactly why
    /// the test drives BOTH halves through the same call site rather than
    /// asserting Start and Stop separately — a stub that special-cased
    /// "first call" would still have passed a Start-only test. Restoring
    /// the real `toggle_action` match made both halves pass again.
    #[cfg(unix)]
    #[test]
    fn dispatches_start_then_stop_through_the_router() {
        let (app, sup) = app_with_supervisor();
        sup.register(sleepy_spec("nginx"));
        assert_eq!(
            sup.snapshot()[0].state,
            ServiceState::Stopped,
            "precondition: freshly registered services start Stopped"
        );

        // toggle_action(Stopped) => Start — the router must bring it up.
        handle_tray_menu_id(app.handle(), "nginx");
        wait_until(
            || {
                sup.snapshot()
                    .iter()
                    .any(|s| s.id == "nginx" && s.state == ServiceState::Running)
            },
            Duration::from_secs(5),
            "router did not start nginx (never reached Running)",
        );

        // toggle_action(Running) => Stop — the SAME router call, now with
        // the service in a different state, must stop it instead. Nothing
        // about the call site changed; only `Supervisor::snapshot()`'s
        // answer did — this is the "never trusts the rendered label"
        // property the whole router is built around.
        handle_tray_menu_id(app.handle(), "nginx");
        wait_until(
            || {
                sup.snapshot()
                    .iter()
                    .any(|s| s.id == "nginx" && s.state == ServiceState::Stopped)
            },
            Duration::from_secs(5),
            "router did not stop nginx (never reached Stopped)",
        );
    }

    /// `toggle_action` answers `Action::None` for a `Starting` row (spec
    /// D3) — the router must honour that and NOT call `stop` on a service
    /// still coming up. Exercised by racing a click immediately after
    /// `start`, before the 500ms `AliveAfter` readiness window elapses.
    ///
    /// `#[tokio::test]`, unlike this module's other router tests: this one
    /// calls `Supervisor::start` DIRECTLY (as test setup, to reach the
    /// `Starting` precondition deterministically — see the comment below)
    /// rather than only through `handle_tray_menu_id`, and
    /// `Supervisor::start` documents that it "must be called from within a
    /// tokio runtime context" (a bare internal `tokio::spawn`). The
    /// router's OWN dispatch is separately wrapped in
    /// `tauri::async_runtime::spawn` (see `handle_tray_menu_id`'s doc
    /// comment) precisely so it does not share this requirement with its
    /// caller — but a direct test setup call is not the router, and does.
    ///
    /// `flavor = "multi_thread"`, not the default single-threaded flavor:
    /// the spawned service task (which must independently progress
    /// `Starting` -> `Running` on ITS OWN 500ms timer) and this test's own
    /// `wait_until` polling loop (a blocking `std::thread::sleep`, not an
    /// `.await`) both live on this same runtime once `sup.start` is called
    /// from inside it. On a single worker thread the poll loop never
    /// yields the thread back to the scheduler, so the service task would
    /// starve and the test would time out regardless of whether the
    /// router behaved correctly — a multi-threaded runtime gives the two
    /// tasks separate OS threads so they do not compete.
    #[cfg(unix)]
    #[tokio::test(flavor = "multi_thread", worker_threads = 2)]
    async fn a_starting_service_is_not_stopped_by_the_router() {
        let (app, sup) = app_with_supervisor();
        sup.register(sleepy_spec("nginx"));
        sup.start("nginx").expect("start failed");
        assert_eq!(
            sup.snapshot()[0].state,
            ServiceState::Starting,
            "precondition: still inside the AliveAfter(500ms) window"
        );

        handle_tray_menu_id(app.handle(), "nginx");

        // Give a wrongly-dispatching implementation time to act, then
        // assert the service reached Running on its OWN (the readiness
        // window elapsing), not because it was stopped-and-restarted.
        wait_until(
            || {
                sup.snapshot()
                    .iter()
                    .any(|s| s.id == "nginx" && s.state == ServiceState::Running)
            },
            Duration::from_secs(5),
            "nginx never reached Running on its own",
        );
    }

    // -----------------------------------------------------------------
    // handle_tray_menu_id: the quit id still delegates correctly (a
    // regression net for moving this logic out of lib.rs's on_menu_event
    // closure and into this shared router).
    // -----------------------------------------------------------------

    #[test]
    fn quit_id_falls_through_to_perform_quit_when_ui_never_acked() {
        let app = tauri::test::mock_builder()
            .build(tauri::test::mock_context(tauri::test::noop_assets()))
            .unwrap();
        // No `UiReady` managed — `request_quit` reports "cannot ask", so
        // this must take the `perform_quit` fallback branch rather than
        // silently doing nothing. `perform_quit` itself will fail (no
        // "main" window in this mock context) and log to stderr; the
        // claim under test is that it was REACHED at all and did not
        // panic, exactly like `perform_quit`'s own direct callers in
        // `lib.rs`.
        handle_tray_menu_id(app.handle(), crate::quit::QUIT_MENU_ITEM_ID);
        // The dispatch is asynchronous (spawned) — briefly yield so a
        // panicking implementation would have had a chance to surface
        // before this test process exits.
        std::thread::sleep(Duration::from_millis(50));
    }

    // -----------------------------------------------------------------
    // handle_tray_menu_id: "Open OpenVHost" is best-effort with no window.
    // -----------------------------------------------------------------

    #[test]
    fn open_id_does_not_panic_when_no_main_window_exists() {
        let (app, _sup) = app_with_supervisor();
        // `mock_context(noop_assets())` creates no "main" window — this
        // must be a silent best-effort no-op, not a panic, mirroring
        // `request_quit`'s own "no window" handling.
        handle_tray_menu_id(app.handle(), OPEN_MENU_ITEM_ID);
    }
}
